
# GRUPO Nº 8


📝 Integrantes:

   1. Acosta, Carla
   2. Barrera, Cristian
   3. Chuchuca, Fanny
   4. Colmenares, Carlos
   5. González, Yanina
   6. Laya, Nicolás
   7. Olave Portilla, Nicolás
   8. Relañez, Alejandro
   9. Parra, Agustín
   10. Pintos, Iván

In [234]:
#import de módulos necesarios a utilizar
import pandas as pd
import re
import random
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [235]:
data_location = "properatti.csv"
data = pd.read_csv(data_location)

Para comenzar, hacemos un análisis general de la base a trabajar. Miramos la cantidad de registros y de variables, y seleccionamos una muestra aleatoria para analizar el contenido:

In [236]:
print(data.shape)
data.sample(10)

(121220, 26)


Unnamed: 0 operation property_type         place_name  \
4423          4423      sell            PH      Mar del Plata   
113890      113890      sell     apartment            Caseros   
26079        26079      sell     apartment            Rosario   
74655        74655      sell     apartment              Haedo   
12546        12546      sell         house          Ituzaingó   
39164        39164      sell            PH      Mar del Plata   
79553        79553      sell     apartment            Almagro   
93596        93596      sell         house  Haras Santa Maria   
105629      105629      sell         house           Nordelta   
87877        87877      sell     apartment            Córdoba   

                                  place_with_parent_names country_name  \
4423    |Argentina|Buenos Aires Costa Atlántica|Mar de...    Argentina   
113890  |Argentina|Bs.As. G.B.A. Zona Oeste|Tres de Fe...    Argentina   
26079                        |Argentina|Santa Fe|Rosario|    Argentina   
74655    |Argentina|Bs.As. G.B.A. Zona Oeste|Morón|Haedo|    Argentina   
12546      |Argentina|Bs.As. G.B.A. Zona Oeste|Ituzaingó|    Argentina   
39164   |Argentina|Buenos Aires Costa Atlántica|Mar de...    Argentina   
79553                 |Argentina|Capital Federal|Almagro|    Argentina   
93596   |Argentina|Bs.As. G.B.A. Zona Norte|Escobar|Ha...    Argentina   
105629  |Argentina|Bs.As. G.B.A. Zona Norte|Tigre|Nord...    Argentina   
87877                                 |Argentina|Córdoba|    Argentina   

                          state_name  geonames_id  \
4423    Buenos Aires Costa Atlántica    3430863.0   
113890      Bs.As. G.B.A. Zona Oeste    3862356.0   
26079                       Santa Fe    3838574.0   
74655       Bs.As. G.B.A. Zona Oeste          NaN   
12546       Bs.As. G.B.A. Zona Oeste    3433359.0   
39164   Buenos Aires Costa Atlántica    3430863.0   
79553                Capital Federal    3436397.0   
93596       Bs.As. G.B.A. Zona Norte          NaN   
105629      Bs.As. G.B.A. Zona Norte          NaN   
87877                        Córdoba    3860255.0   

                              lat-lon        lat  ...  surface_covered_in_m2  \
4423           -38.0166869,-57.570879 -38.016687  ...                   65.0   
113890        -34.6068156,-58.5692826 -34.606816  ...                   45.0   
26079         -32.9387556,-60.6576955 -32.938756  ...                   31.0   
74655                             NaN        NaN  ...                   45.0   
12546         -34.6558182,-58.6825274 -34.655818  ...                  140.0   
39164          -38.011269,-57.5437023 -38.011269  ...                  110.0   
79553   -34.6213482616,-58.4203806533 -34.621348  ...                   35.0   
93596                             NaN        NaN  ...                  247.0   
105629                            NaN        NaN  ...                    NaN   
87877                             NaN        NaN  ...                   44.0   

        price_usd_per_m2  price_per_m2  floor  rooms  expenses  \
4423                 NaN   1230.769231    NaN    2.0       NaN   
113890       1560.000000   1733.333333    NaN    NaN       NaN   
26079       37096.774194  37096.774194    NaN    1.0       NaN   
74655                NaN   1644.444444    NaN    NaN       NaN   
12546         447.368421   1214.285714    NaN    NaN       NaN   
39164                NaN           NaN    NaN    4.0       NaN   
79553        1945.945946   2057.142857    NaN    NaN       NaN   
93596                NaN   1295.546559    NaN    NaN       NaN   
105629       1936.842105           NaN    NaN    NaN       NaN   
87877        1231.641373  25454.545455    NaN    NaN       NaN   

                                            properati_url  \
4423    http://www.properati.com.ar/15mtf_venta_ph_mar...   
113890  http://www.properati.com.ar/1c922_venta_depart...   
26079   http://www.properati.com.ar/17qqc_venta_depart...   
74655   http://www.properati.com.ar/1ap9k

In [237]:
data.operation.value_counts()

sell    121220
Name: operation, dtype: int64

Analizamos el tipo de datos de cada columna e información sobre la distribución de los datos:

In [238]:
data.dtypes

Unnamed: 0                      int64
operation                      object
property_type                  object
place_name                     object
place_with_parent_names        object
country_name                   object
state_name                     object
geonames_id                   float64
lat-lon                        object
lat                           float64
lon                           float64
price                         float64
currency                       object
price_aprox_local_currency    float64
price_aprox_usd               float64
surface_total_in_m2           float64
surface_covered_in_m2         float64
price_usd_per_m2              float64
price_per_m2                  float64
floor                         float64
rooms                         float64
expenses                      float64
properati_url                  object
description                    object
title                          object
image_thumbnail                object
dtype: objec

In [239]:
data.describe()

Unnamed: 0   geonames_id           lat           lon         price  \
count  121220.000000  1.025030e+05  69670.000000  69670.000000  1.008100e+05   
mean    60609.500000  3.574442e+06    -34.626210    -59.266290  4.685259e+05   
std     34993.344153  3.541306e+05      1.980936      2.299922  2.260101e+06   
min         0.000000  3.427208e+06    -54.823985    -75.678931  0.000000e+00   
25%     30304.750000  3.430234e+06    -34.669065    -58.727040  1.100000e+05   
50%     60609.500000  3.433910e+06    -34.597985    -58.480128  1.850000e+05   
75%     90914.250000  3.836668e+06    -34.441299    -58.395908  4.200000e+05   
max    121219.000000  6.948895e+06      4.545843    -53.733330  6.500000e+08   

       price_aprox_local_currency  price_aprox_usd  surface_total_in_m2  \
count                1.008100e+05     1.008100e+05         81892.000000   
mean                 4.229397e+06     2.397006e+05           233.795328   
std                  6.904714e+06     3.913239e+05          1782.222147   
min                  0.000000e+00     0.000000e+00             0.000000   
25%                  1.583309e+06     8.973388e+04            50.000000   
50%                  2.558452e+06     1.450000e+05            84.000000   
75%                  4.675792e+06     2.650000e+05           200.000000   
max                  8.212711e+08     4.654544e+07        200000.000000   

       surface_covered_in_m2  price_usd_per_m2  price_per_m2        floor  \
count          101313.000000      68617.000000  8.765800e+04  7899.000000   
mean              133.050181       2160.086916  6.912216e+03    17.452336   
std               724.351479       2759.288621  2.837864e+04   120.243621   
min                 0.000000          0.600000  1.510204e+00     1.000000   
25%                45.000000       1218.181818  1.550000e+03     1.000000   
50%                75.000000       1800.000000  2.213115e+03     3.000000   
75%               150.000000       2486.411765  3.355549e+03     6.000000   
max            187000.000000     206333.333333  4.000000e+06  3150.000000   

              rooms      expenses  
count  47390.000000  1.426200e+04  
mean       3.080840  5.009234e+03  
std        1.860773  1.204403e+05  
min        1.000000  1.000000e+00  
25%        2.000000  1.000000e+03  
50%        3.000000  2.000000e+03  
75%        4.000000  4.000000e+03  
max       32.000000  1.000150e+07

Por último, analizamos la cantidad y el porcentaje de valores nulos por columna.

In [240]:
print("Cantidad de nulos por columna:")
print(data.isnull().sum())
print("----------------------------------")
print("Porcentaje de nulos por columna:")
((data.isnull().sum()/data.shape[0]*100).round(2)).sort_values()

Cantidad de nulos por columna:
Unnamed: 0                         0
operation                          0
property_type                      0
place_name                        23
place_with_parent_names            0
country_name                       0
state_name                         0
geonames_id                    18717
lat-lon                        51550
lat                            51550
lon                            51550
price                          20410
currency                       20411
price_aprox_local_currency     20410
price_aprox_usd                20410
surface_total_in_m2            39328
surface_covered_in_m2          19907
price_usd_per_m2               52603
price_per_m2                   33562
floor                         113321
rooms                          73830
expenses                      106958
properati_url                      0
description                        2
title                              0
image_thumbnail                 3112
dtype: 

Unnamed: 0                     0.00
operation                      0.00
property_type                  0.00
place_with_parent_names        0.00
country_name                   0.00
state_name                     0.00
description                    0.00
properati_url                  0.00
title                          0.00
place_name                     0.02
image_thumbnail                2.57
geonames_id                   15.44
surface_covered_in_m2         16.42
price                         16.84
price_aprox_local_currency    16.84
price_aprox_usd               16.84
currency                      16.84
price_per_m2                  27.69
surface_total_in_m2           32.44
lat                           42.53
lat-lon                       42.53
lon                           42.53
price_usd_per_m2              43.39
rooms                         60.91
expenses                      88.23
floor                         93.48
dtype: float64

#### CONCLUSIONES PRELIMINARES 📌

Tenemos un dataset con 121220 registros y 26 variables.

De las 26 variables:
    
   * 10 variables no contienen nulos
   * 7 variables tienen menos del 20% de nulos
   * 6 variables contienen entre 20% y 50% de nulos
   * 3 variables contienen más de 50% de nulos (dos de ellas por encima del 85%)
    
Luego de este primer análisis, decidimos prescindir de columnas que no tienen valor para el futuro modelo de predicción. Serán eliminadas posteriormente a la hora de definir el dataset final. 

   * *Unnamed: 0*: su valor es idéntico al del index. 
   * *Operation*: su único valor es "sell", por lo que todos los registros refieren a ventas de una propiedad.
   * *place_with_parent_names*: su función es concatenar valores de *country_name, *place_name* y *state_name*. Por lo tanto esa información esta presentre en otras columnas y en un formato más útil para trabajar.
   * *country_name*: su único valor es Argentina, por lo que podemos trabajar bajo el supuesto de que todas las ventas ocurrieron en ese país.
   * *properati_url*: no contiene información relevante.
   * *image_thumbnail*: no contiene información relevante.
   * *expenses*: contiene un porcentaje muy alto de nulos. 
   
      
Con las variables restantes, de acuerdo a la información que contienen, decidimos agruparlas en "secciones" para trabajarlas mejor: 

1. Columnas relativas a la ubicación geográfica de la propiedad
2. Columnas con información descriptiva sobre la propiedad
3. Columnas referidas al valor de la propiedad.
    


## SECCIÓN 1 - COLUMNAS GEOGRÁFICAS
----------------

1. place_name
2. geonames_id
3. lat
4. lon
5. lat-lon


Armamos un df reducido las columnas de interés para esta sección.

In [241]:
data_geo = data[["geonames_id","lat","lon","lat-lon"]]
data_geo.head(5)

geonames_id        lat        lon                  lat-lon
0    3430787.0 -34.661824 -58.508839  -34.6618237,-58.5088387
1    3432039.0 -34.903883 -57.964330  -34.9038831,-57.9643295
2    3430787.0 -34.652262 -58.522982  -34.6522615,-58.5229825
3    3431333.0 -34.647797 -58.516424  -34.6477969,-58.5164244
4    3435548.0 -38.002626 -57.549447  -38.0026256,-57.5494468

**Tipos de las columnas**. Hay 3 en formato numérico, y 1 de tipo *object*, que combina los datos de latitud y longitud.

In [242]:
print(data_geo.dtypes)
print(data_geo.shape)

geonames_id    float64
lat            float64
lon            float64
lat-lon         object
dtype: object
(121220, 4)


**Porcentaje de nulos**.
La columna *geonames_id* tiene un % sensiblemente menor de nulos que las otras 3 columnas. 
Las columnas *lat-lon*, *lat* y *lon*, además de tener un % alto (42,5), tienen la misma cantidad de nulos.

In [243]:
print("Cantidad de nulos por columna:")
print(data_geo.isnull().sum())
print("------------------------")
print("Porcentaje de nulos por columna:")
porc_nulos = (data_geo.isnull().sum() / data_geo.shape[0] *100).round(2)
porc_nulos.sort_values(ascending=False)

Cantidad de nulos por columna:
geonames_id    18717
lat            51550
lon            51550
lat-lon        51550
dtype: int64
------------------------
Porcentaje de nulos por columna:


lat            42.53
lon            42.53
lat-lon        42.53
geonames_id    15.44
dtype: float64

---

#### SECCION 1.1 - LAT, LON, LAT-LON


 #### ANÁLISIS 🔎


Presumiblemente, los nulos corresponden a las mismas filas y por lo tanto no podemos recuperar información entre ellas.


Para comprobar esto, creamos un nuevo df con los nulos en la variable "lat", que contiene las 3 columnas de interés.

In [244]:
mask_lat_null = data_geo["lat"].isnull()
lat_null = data_geo.loc[mask_lat_null,["lat","lon","lat-lon"]]
lat_null

lat  lon lat-lon
13      NaN  NaN     NaN
14      NaN  NaN     NaN
23      NaN  NaN     NaN
42      NaN  NaN     NaN
49      NaN  NaN     NaN
...     ...  ...     ...
121214  NaN  NaN     NaN
121215  NaN  NaN     NaN
121216  NaN  NaN     NaN
121218  NaN  NaN     NaN
121219  NaN  NaN     NaN

[51550 rows x 3 columns]

Luego miramos la cantidad de nulos de ese df, pero sobre el axis 1, es decir, las filas. 
Al contar los valores, vemos que para todas las filas (51550) nos devuelve 3 nulos por fila. Por lo tanto, todos los nulos en *lat* son también nulos en *lon* y en *lat-lon*:

In [245]:
cant_nulos_xfila = lat_null.isnull().sum(axis=1)
print(cant_nulos_xfila.value_counts())

3    51550
dtype: int64


Otra manera de comprobar esto es utilizando el método .equals para comparar las series.

In [246]:
print("¿'lat' y 'lon' son iguales?", lat_null["lat"].equals(lat_null["lon"])) #en .equals, los nulos ubicados en la misma posición son considerados iguales. 

¿'lat' y 'lon' son iguales? True


In [247]:
lat_null["lat_object"] = lat_null["lat"].astype("object") #creamos una nueva col "lat_object" ccambiendole el tipo a "lat" para poder aplicar la comparación con "lat-lon"
print("¿'lat' y 'lat-lon' son iguales?", lat_null["lat_object"].equals(lat_null["lat-lon"]))

¿'lat' y 'lat-lon' son iguales? True


✔️ Demostramos que las 3 columnas son iguales entre sí. 

In [248]:
#data.description.to_csv("description_original")
#data.title.to_csv("title_original")

#### CONCLUSIÓN 📌
Si bien podrían recuperarse algunos valores (101) aplicando expresiones regulares en la columna *description*, consideramos que la ubicación geográfica exacta del inmueble (valores de latitud y longitud) es un dato muy específico que **no es determinante a la hora de predecir el precio por m2**.

Tampoco parece tener sentido intentar alguna estrategia de imputación: no podemos utilizar ninguna medida de tendencia de las columnas porque no serían representativas del punto geográfico, ni tampoco podemos asociar la info de latitud y longitud a la información contenida en otras variables.

Por otra parte, la variable precio suele responder a datos más generales como barrio o localidad. Por lo tanto las columnas "geoname_id" o "place_name"
pueden ser mas útiles.

---

#### SECCIÓN 1. 2 - GEONAMES_ID, PLACE_NAME

 #### ANÁLISIS 🔎

Queremos analizar a qué variable/s o criterio geográfico responde la columna *geonames_id*.


Creamos un nuevo df agregando otras variables que nos pueden servir para ello, y como como primer paso, analizamos si hay IDs que se repiten. En efecto algunos aparecen con mas frecuencia que otros:

In [249]:
data_geonames = data.loc[:,["geonames_id","place_name","state_name","country_name","place_with_parent_names","lat","lon","lat-lon"]]

In [250]:
ocurrencia_ids = data_geonames.geonames_id.value_counts().sort_values(ascending=False)
print("Ocurrencia de IDS (sin nulos):")
print(ocurrencia_ids)

Ocurrencia de IDS (sin nulos):
3838574.0    8504
3860259.0    6606
3430863.0    6534
3430234.0    3279
3436077.0    2992
             ... 
3433325.0       1
3432077.0       1
3855368.0       1
3844759.0       1
3430940.0       1
Name: geonames_id, Length: 646, dtype: int64


Haciendo un .head() sobre el df nuevo, podemos intuir que *geonames_id* es un valor único asociado a la localidad, dado que observaciones que tienen un mismo *state_name* y *country_name* pero diferente *place_name* (y por lo tanto diferente *place_with_parent_names*) tienen distintos valores para *geonames_id*. 
Ej: "Mataderos" vs "Liniers"

In [251]:
data_geonames.head(5)

geonames_id place_name                    state_name country_name  \
0    3430787.0  Mataderos               Capital Federal    Argentina   
1    3432039.0   La Plata        Bs.As. G.B.A. Zona Sur    Argentina   
2    3430787.0  Mataderos               Capital Federal    Argentina   
3    3431333.0    Liniers               Capital Federal    Argentina   
4    3435548.0     Centro  Buenos Aires Costa Atlántica    Argentina   

                             place_with_parent_names        lat        lon  \
0              |Argentina|Capital Federal|Mataderos| -34.661824 -58.508839   
1        |Argentina|Bs.As. G.B.A. Zona Sur|La Plata| -34.903883 -57.964330   
2              |Argentina|Capital Federal|Mataderos| -34.652262 -58.522982   
3                |Argentina|Capital Federal|Liniers| -34.647797 -58.516424   
4  |Argentina|Buenos Aires Costa Atlántica|Mar de... -38.002626 -57.549447   

                   lat-lon  
0  -34.6618237,-58.5088387  
1  -34.9038831,-57.9643295  
2  -34.6522615,-58.5229825  
3  -34.6477969,-58.5164244  
4  -38.0026256,-57.5494468

A continuación contamos los valores únicos de cada columna (quitando los nulos), para ver si hay correspondencia.

In [252]:
mask_geo_id_not_null = data_geonames["geonames_id"].notnull()
geo_id_not_null = data_geonames.geonames_id[mask_geo_id_not_null] 

mask_place_name_not_null = data_geonames["place_name"].notnull()
place_name_not_null = data_geonames.place_name[mask_place_name_not_null]

mask_pwpn_not_null = data_geonames["place_with_parent_names"].notnull()
pwpn_not_null = data_geonames.place_with_parent_names[mask_pwpn_not_null]

In [253]:
print("Cantidad de valores únicos en geonames_id:", len(geo_id_not_null.unique()))
print("Cantidad de valores únicos en place_name:", len(place_name_not_null.unique()))
print("Cantidad de valores únicos en place_with_parent_names:", len(pwpn_not_null.unique()))

Cantidad de valores únicos en geonames_id: 646
Cantidad de valores únicos en place_name: 1060
Cantidad de valores únicos en place_with_parent_names: 1164



Vemos que hay mayor cantidad de valores unicos de *place_with_parent_names* y de *place_name*, que de *geonames_id*. Esto puede deberse a que hay  mayor cantidad de nulos en esa columna con respecto a las otras dos. **Pero también puede suceder que haya geo id's que estén asociados a más de una localidad, lo que sería un error de la base.**

Para comprobar esto hacemos una agrupación por ID, y contamos cuantos valores únicos de *place_name* hay para cada uno. 
Luego, aplicando una máscara, vemos que hay solo 5 ids que tienen más de un valor asociado. 

In [254]:
#lo vamos a hacer sobre valores no nulos de geonames_ID.
mask_geoid_notnull = data_geonames["geonames_id"].notnull()
data_geonames_notnull = data_geonames.loc[mask_geoid_notnull]
data_geonames_notnull.shape

(102503, 8)

In [255]:
place_name_by_id = data_geonames_notnull.groupby(["geonames_id"])["place_name"].nunique().sort_values(ascending = False)
place_name_by_id
mask_place_name_by_id = place_name_by_id > 1
id_multi_place_name = place_name_by_id[mask_place_name_by_id]
print(id_multi_place_name)
print("Cantidad geo ids con más de una localidad: ", len(place_name_by_id[mask_place_name_by_id]))

geonames_id
3435907.0    5
3435548.0    2
3428927.0    2
3433359.0    2
3430234.0    2
Name: place_name, dtype: int64
Cantidad geo ids con más de una localidad:  5


In [256]:
indices = id_multi_place_name.index #nos quedamos con los índices para crear una máscara
mask_indices = data_geonames_notnull["geonames_id"].isin(indices)
data_geonames_multi_localidad = data_geonames_notnull.loc[mask_indices]

Con un groupby listamos los valores que tiene cada uno de estos 5 geo id para *place_name*, pero junto a los valores de *state_name* para tener mayor información sobre la localidad. 

Para ver los valores que agrupa cada ID, agregamos el método .agg, que nos lista cada uno de los valores posibles para cada variable

In [257]:
place_name_by_id_values = data_geonames_multi_localidad.groupby("geonames_id").agg({'place_name': 'unique', 'state_name': 'unique'}).reset_index()
place_name_by_id_values

geonames_id                                         place_name  \
0    3428927.0                               [San José, San Jose]   
1    3430234.0                            [Palermo Soho, Palermo]   
2    3433359.0                         [Ituzaingó, Villa Udaondo]   
3    3435548.0                     [Centro, Centro / Microcentro]   
4    3435907.0  [Bs.As. G.B.A. Zona Sur, Buenos Aires Interior...   

                                          state_name  
0                           [Bs.As. G.B.A. Zona Sur]  
1                                  [Capital Federal]  
2                         [Bs.As. G.B.A. Zona Oeste]  
3    [Buenos Aires Costa Atlántica, Capital Federal]  
4  [Bs.As. G.B.A. Zona Sur, Buenos Aires Interior...

En la salida anterior podemos ver que vemos que solamente los ultimos dos casos refieren a localidades distintas, ya que se encuentran en diferentes regiones.

#### CONCLUSIÓN 📌 

Asumimos que estos casos son errores y que **cada localidad debería tener un *geoname_id* unico.**

#### LIMPIEZA DE DATOS 📝

Procedemos a limpiar los primeros 3 casos, dejando solo un valor de circunscripción:

* **Para eso, creamos una nueva variable *place_name_new***

In [258]:
data["place_name_new"] = data["place_name"]
data["place_name_new"] = data["place_name_new"].replace("San Jose", "San José")
data["place_name_new"] = data["place_name_new"].replace("Palermo Soho", "Palermo")
data["place_name_new"] = data["place_name_new"].replace("Villa Udaondo", "Ituzaingó")

Miramos los otros dos casos:

In [259]:
#buenos aires
mask_3435907 = data["geonames_id"] == 3435907.0
data_3435907 = data.loc[mask_3435907,["geonames_id","place_name","place_with_parent_names","state_name","title","description","lat"]]
data_3435907

geonames_id                place_name  \
125       3435907.0    Bs.As. G.B.A. Zona Sur   
433       3435907.0     Buenos Aires Interior   
664       3435907.0     Buenos Aires Interior   
897       3435907.0     Buenos Aires Interior   
1022      3435907.0     Buenos Aires Interior   
...             ...                       ...   
117729    3435907.0  Bs.As. G.B.A. Zona Norte   
118326    3435907.0  Bs.As. G.B.A. Zona Norte   
118493    3435907.0  Bs.As. G.B.A. Zona Norte   
118819    3435907.0  Bs.As. G.B.A. Zona Norte   
121141    3435907.0  Bs.As. G.B.A. Zona Norte   

                     place_with_parent_names                state_name  \
125       |Argentina|Bs.As. G.B.A. Zona Sur|    Bs.As. G.B.A. Zona Sur   
433        |Argentina|Buenos Aires Interior|     Buenos Aires Interior   
664        |Argentina|Buenos Aires Interior|     Buenos Aires Interior   
897        |Argentina|Buenos Aires Interior|     Buenos Aires Interior   
1022       |Argentina|Buenos Aires Interior|     Buenos Aires Interior   
...                                      ...                       ...   
117729  |Argentina|Bs.As. G.B.A. Zona Norte|  Bs.As. G.B.A. Zona Norte   
118326  |Argentina|Bs.As. G.B.A. Zona Norte|  Bs.As. G.B.A. Zona Norte   
118493  |Argentina|Bs.As. G.B.A. Zona Norte|  Bs.As. G.B.A. Zona Norte   
118819  |Argentina|Bs.As. G.B.A. Zona Norte|  Bs.As. G.B.A. Zona Norte   
121141  |Argentina|Bs.As. G.B.A. Zona Norte|  Bs.As. G.B.A. Zona Norte   

                                                    title  \
125                                              RUGGIERI   
433     Casa de 3 dormitorios con dependencia en Estan...   
664     [B.I 0527] VILLA GESELL - FRENTE AL MAR, DEPAR...   
897      BENQUERENCIA EXC CHACRA UBICACIÓN Y CONSTRUCCIÓN   
1022                       CASA EN VENTA FLORENCIO VARELA   
...                                                   ...   
117729  Importante Casa en Venta en Campana Centro. 3 ...   
118326                    Departamento - Cardales Village   
118493                          Local - Jose Clemente Paz   
118819  Departamento en Venta en Campana Centro. 4 dor...   
121141  Excelente CASA a ESTRENAR APTA CREDITO - La Re...   

                                              description        lat  
125     CODIGO: 438-12112 ubicado en: test de prueba -... -38.416097  
433     CODIGO: 157-AW23557 ubicado en: La Pionera -  ... -38.416097  
664     CODIGO:  ubicado en: [B.I 0527] VILLA GESELL -... -38.416097  
897     Corredor Responsable: Ramiro Cappelloni - C.M....        NaN  
1022    CODIGO: 3836-789 ubicado en: Republica de Urug... -38.416097  
...                                                   ...        ...  
117729  Excelente Casa en venta en Campana Centro. Zon...        NaN  
118326  Departamento en Terrazas Cardales en venta, de...        NaN  
118493  VENTA IMPORTANTE LOCAL COMERCIAL CON FRENTE A ...        NaN  
118819  El departamento consta de living comedor, coci...        NaN  
121141  RUCA INMUEBLES - 011-15- / 011- -  -  CASA a E...        NaN  

[444 rows x 7 columns]

Vemos que son 444 registros que pertenecen a la provincia de BSAS, de los que no podemos inferir una localidad fácilmente (no habría un patrón claro para diseñar una expresión regular para *title* o *description*). Sin embargo los dejamos porque a la hora de predecir el precio podríamos hacerlo al nivel de *state_name*.

Lo que decidimos hacer es asignarles un *place_name* nuevo que refiera a sin identificar:

In [260]:
data.loc[mask_3435907,"place_name_new"] = "Sin Identificar"

Verificamos el cambio:

In [261]:
data.loc[mask_3435907,["geonames_id","place_name","place_name_new"]]

geonames_id                place_name   place_name_new
125       3435907.0    Bs.As. G.B.A. Zona Sur  Sin Identificar
433       3435907.0     Buenos Aires Interior  Sin Identificar
664       3435907.0     Buenos Aires Interior  Sin Identificar
897       3435907.0     Buenos Aires Interior  Sin Identificar
1022      3435907.0     Buenos Aires Interior  Sin Identificar
...             ...                       ...              ...
117729    3435907.0  Bs.As. G.B.A. Zona Norte  Sin Identificar
118326    3435907.0  Bs.As. G.B.A. Zona Norte  Sin Identificar
118493    3435907.0  Bs.As. G.B.A. Zona Norte  Sin Identificar
118819    3435907.0  Bs.As. G.B.A. Zona Norte  Sin Identificar
121141    3435907.0  Bs.As. G.B.A. Zona Norte  Sin Identificar

[444 rows x 3 columns]

In [262]:
#costa atlántica/microcentro
mask_3435548 = data["geonames_id"] == 3435548.0
data_3435548 = data.loc[mask_3435548,["geonames_id","place_name","place_with_parent_names","state_name","title","description","lat","lon"]]
data_3435548

geonames_id            place_name  \
4         3435548.0                Centro   
1539      3435548.0  Centro / Microcentro   
1649      3435548.0  Centro / Microcentro   
1657      3435548.0  Centro / Microcentro   
4299      3435548.0  Centro / Microcentro   
...             ...                   ...   
117949    3435548.0                Centro   
118139    3435548.0                Centro   
118900    3435548.0                Centro   
119500    3435548.0                Centro   
119744    3435548.0  Centro / Microcentro   

                                  place_with_parent_names  \
4       |Argentina|Buenos Aires Costa Atlántica|Mar de...   
1539     |Argentina|Capital Federal|Centro / Microcentro|   
1649     |Argentina|Capital Federal|Centro / Microcentro|   
1657     |Argentina|Capital Federal|Centro / Microcentro|   
4299     |Argentina|Capital Federal|Centro / Microcentro|   
...                                                   ...   
117949  |Argentina|Buenos Aires Costa Atlántica|Mar de...   
118139  |Argentina|Buenos Aires Costa Atlántica|Mar de...   
118900  |Argentina|Buenos Aires Costa Atlántica|Mar de...   
119500  |Argentina|Buenos Aires Costa Atlántica|Mar de...   
119744   |Argentina|Capital Federal|Centro / Microcentro|   

                          state_name  \
4       Buenos Aires Costa Atlántica   
1539                 Capital Federal   
1649                 Capital Federal   
1657                 Capital Federal   
4299                 Capital Federal   
...                              ...   
117949  Buenos Aires Costa Atlántica   
118139  Buenos Aires Costa Atlántica   
118900  Buenos Aires Costa Atlántica   
119500  Buenos Aires Costa Atlántica   
119744               Capital Federal   

                                                    title  \
4       DEPTO 2 AMB AL CONTRAFRENTE ZONA CENTRO/PLAZA ...   
1539               Departamento a la Venta en Microcentro   
1649                                DEPARTAMENTO EN VENTA   
1657                                       LOCAL EN VENTA   
4299                                     EXCELENTE LOCAL    
...                                                   ...   
117949                              Departamento - Centro   
118139                              Departamento - Centro   
118900                              Departamento - Centro   
119500  PH de 2 ambientes con patio, sin gastos de exp...   
119744   Extraordinario Local en Plaza San Martín - ÚNICO   

                                              description        lat  \
4       DEPARTAMENTO CON FANTÁSTICA ILUMINACIÓN NATURA... -38.002626   
1539    Corredor Responsable: Ricardo Demichelli - CUC... -34.598825   
1649    Venta de Departamento MONOAMBIENTE en Centro /... -34.603273   
1657    LOCALVenta y alquiler de Local  en Centro / Mi... -34.599865   
4299    El local forma parte de la "Casa de estudios p... -34.598051   
...                                                   ...        ...   
117949  Departamento 28m² con Gas Natural, Mar del Pla...        NaN   
118139  Excelente departamento ubicado en zona centro ...        NaN   
118900  Edificio FLORIDA 1. Piso alto, balcón francés....        NaN   
119500  PH de 2 ambientes con posibilidad de ampliació... -38.000113   
119744  Corredor Responsable: Cristian Arnal Ponti - C... -34.596671   

              lon  
4      -57.549447  
1539   -58.371456  
1649   -58.396141  
1657   -58.375840  
4299   -58.379729  
...           ...  
117949        NaN  
118139        NaN  
118900        NaN  
119500 -57.564401  
119744 -58.375490  

[454 rows x 8 columns]

Vemos que son 454 registros. Decidimos reemplazar el valor "Centro / Microcentro" por el barrio de San Nicolás, que es la región que comprende el microcentro en CABA. 
Al valor de "Centro" de Mar del Plata, le dejamos el ID que venía por defecto. 

In [263]:
data["place_name_new"] = data["place_name_new"].replace("Centro / Microcentro", "San Nicolás")

Le asignamos el ID que le corresponde según https://www.geonames.org/6693229/san-nicolas.html.

* **Para eso, creamos una nueva columna de geonames_id_new.**

In [264]:
data["geonames_id_new"] = data["geonames_id"]
mask_san_nicolas = data["place_name_new"] == "San Nicolás"
data.loc[mask_san_nicolas,"geonames_id_new"] = 6693229.0

data.loc[mask_san_nicolas, ["place_name","geonames_id"
                            ,"place_name_new","geonames_id_new"]]

place_name  geonames_id place_name_new  geonames_id_new
876              San Nicolás    6693229.0    San Nicolás        6693229.0
1539    Centro / Microcentro    3435548.0    San Nicolás        6693229.0
1649    Centro / Microcentro    3435548.0    San Nicolás        6693229.0
1657    Centro / Microcentro    3435548.0    San Nicolás        6693229.0
2841             San Nicolás    6693229.0    San Nicolás        6693229.0
...                      ...          ...            ...              ...
117158           San Nicolás    6693229.0    San Nicolás        6693229.0
118719           San Nicolás    6693229.0    San Nicolás        6693229.0
119319           San Nicolás    6693229.0    San Nicolás        6693229.0
119744  Centro / Microcentro    3435548.0    San Nicolás        6693229.0
119874           San Nicolás    6693229.0    San Nicolás        6693229.0

[410 rows x 4 columns]

✔️ Comprobamos que ya no hay dos valores de *place_name* por id:

In [265]:
place_name_by_id_new = data.groupby(["geonames_id_new"])["place_name_new"].nunique().sort_values(ascending = False)
mask_place_name_new_by_id = place_name_by_id_new > 1
id_multi_place_name_new = place_name_by_id[mask_place_name_new_by_id]
print(id_multi_place_name_new)
print("Cantidad geo ids con más de una localidad: ", len(place_name_by_id_new[mask_place_name_new_by_id]))

Series([], Name: place_name, dtype: int64)
Cantidad geo ids con más de una localidad:  0


---

A continuación hacemos el mismo análisis pero con *state_name*, y en este caso hay 4 geo ids con más de un valor asociado (valores diferentes, lo que indicaría que se trata de un error).

In [266]:
# se crea una nueva state_name_new, que aunque no se utilizará ahora, se integrara al dataset final posteriormente.
data['state_name_new'] = data.state_name

In [267]:
state_name_by_id = data_geonames_notnull.groupby(["geonames_id"])["state_name"].nunique().sort_values(ascending = False)
state_name_by_id
mask_state_name_by_id = state_name_by_id > 1
id_multi_state_name = state_name_by_id[mask_state_name_by_id]
print(id_multi_state_name)
print("Cantidad geo ids con más de una state: ", len(state_name_by_id[mask_state_name_by_id]))

geonames_id
3435907.0    5
3845073.0    2
3435548.0    2
3435024.0    2
Name: state_name, dtype: int64
Cantidad geo ids con más de una state:  4


In [268]:
indices2 = id_multi_state_name.index #nos quedamos con los índices para crear una máscara
mask_indices2 = data_geonames_notnull["geonames_id"].isin(indices2)
data_geonames_multi_state = data_geonames_notnull.loc[mask_indices2]

In [269]:
state_by_id_values = data_geonames_multi_state.groupby("geonames_id").agg({'place_name':'unique','state_name': 'unique', 'place_with_parent_names': 'unique'}).reset_index()
state_by_id_values


geonames_id                                         place_name  \
0    3435024.0                                        [Don Bosco]   
1    3435548.0                     [Centro, Centro / Microcentro]   
2    3435907.0  [Bs.As. G.B.A. Zona Sur, Buenos Aires Interior...   
3    3845073.0                              [Malvinas Argentinas]   

                                          state_name  \
0  [Bs.As. G.B.A. Zona Sur, Buenos Aires Costa At...   
1    [Buenos Aires Costa Atlántica, Capital Federal]   
2  [Bs.As. G.B.A. Zona Sur, Buenos Aires Interior...   
3                  [Bs.As. G.B.A. Zona Sur, Córdoba]   

                             place_with_parent_names  
0  [|Argentina|Bs.As. G.B.A. Zona Sur|Quilmes|Don...  
1  [|Argentina|Buenos Aires Costa Atlántica|Mar d...  
2  [|Argentina|Bs.As. G.B.A. Zona Sur|, |Argentin...  
3  [|Argentina|Bs.As. G.B.A. Zona Sur|Almirante B...

En la salida anterior vemos que dos casos ya estarían normalizados en las columnas *nuevas place_name_new* y *geonames_id_new* según los pasos anteriores ya que se trataba de casos de valores de place_name distintos.

Sin embargo nos quedan dos ID's en los que hay 2 localidades diferentes bajo un mismo nombre de *place_name*.
Podemos saber que son distintas porque pertenecen a distintos state.



Procedemos a normalizar esto. Buscamos los ID correctos para cada localidad, según https://www.geonames.org/

1. Don Bosco - Quilmes: 3435024.0 (es el ID por default en la base. No lo modificamos)
2. Don Bosco - Costa Atlántica: No se encuentra ID. Le asignamos el *geoname_id* y de *place_name* de "Centro" de "Mar del Plata", ya que es un barrio adyacente al centro.
3. Malvinas Argentinas - GBA: 12663166.0
4. Malvinas Argentinas - Córdoba: 3845073.0 (es el ID por default en la base. No lo modificamos)

In [270]:
#don bosco costa atlántica
mask_don_bosco = data["place_name_new"] == "Don Bosco"
mask_catlántica = data["state_name"].str.contains("Costa")
mask_combined = mask_don_bosco & mask_catlántica

In [271]:
#lo aplicamos al df original
data.loc[mask_combined,"geonames_id_new"] = 3435548.0 #valor de centro de mdq
data.loc[mask_combined, ["place_name","geonames_id","state_name"
                            ,"place_name_new","geonames_id_new"]]

place_name  geonames_id                    state_name place_name_new  \
11277  Don Bosco    3435024.0  Buenos Aires Costa Atlántica      Don Bosco   
12081  Don Bosco    3435024.0  Buenos Aires Costa Atlántica      Don Bosco   
12086  Don Bosco    3435024.0  Buenos Aires Costa Atlántica      Don Bosco   
12103  Don Bosco    3435024.0  Buenos Aires Costa Atlántica      Don Bosco   

       geonames_id_new  
11277        3435548.0  
12081        3435548.0  
12086        3435548.0  
12103        3435548.0

In [272]:
#malvinas argentinas GBA 
mask_malvinas = data["place_name_new"] == "Malvinas Argentinas"
mask_GBA = data["state_name"].str.contains("Zona Sur")
mask_combined2 = mask_malvinas & mask_GBA

data.loc[mask_combined2,"geonames_id_new"] = 12663166.0
data.loc[mask_combined2, ["place_name","geonames_id","state_name"
                            ,"place_name_new","geonames_id_new"]]

place_name  geonames_id              state_name  \
67232   Malvinas Argentinas    3845073.0  Bs.As. G.B.A. Zona Sur   
89160   Malvinas Argentinas    3845073.0  Bs.As. G.B.A. Zona Sur   
102972  Malvinas Argentinas    3845073.0  Bs.As. G.B.A. Zona Sur   
102974  Malvinas Argentinas    3845073.0  Bs.As. G.B.A. Zona Sur   
114578  Malvinas Argentinas    3845073.0  Bs.As. G.B.A. Zona Sur   

             place_name_new  geonames_id_new  
67232   Malvinas Argentinas       12663166.0  
89160   Malvinas Argentinas       12663166.0  
102972  Malvinas Argentinas       12663166.0  
102974  Malvinas Argentinas       12663166.0  
114578  Malvinas Argentinas       12663166.0

----

Como comprobación extra, analizamos *place_with_parent_names*. Y obtenemos 40 ID's con más de un valor asociado.

In [273]:
placewpn_by_id = data_geonames_notnull.groupby(["geonames_id"])["place_with_parent_names"].nunique().sort_values(ascending = False)
mask_placewpn_by_id = placewpn_by_id > 1
print("Cantidad geo ids con más de un valor: ", len(placewpn_by_id[mask_placewpn_by_id]))

Cantidad geo ids con más de un valor:  40


In [274]:
pwpn_by_id_values = data.groupby(["geonames_id"])["place_with_parent_names"].unique().agg(list)
id_multi_localidad2 = pwpn_by_id_values.loc[mask_placewpn_by_id]
for geo_id in id_multi_localidad2:
       print (geo_id)

['|Argentina|Bs.As. G.B.A. Zona Norte|San Isidro|Villa Adelina|', '|Argentina|Bs.As. G.B.A. Zona Norte|Vicente López|Villa Adelina|']
['|Argentina|Buenos Aires Interior|Tandil|Tandil|', '|Argentina|Buenos Aires Interior|Tandil|']
['|Argentina|Buenos Aires Interior|San Pedro|San Pedro|', '|Argentina|Buenos Aires Interior|San Pedro|']
['|Argentina|Buenos Aires Interior|San Miguel del Monte|San Miguel del Monte|', '|Argentina|Buenos Aires Interior|San Miguel del Monte|']
['|Argentina|Bs.As. G.B.A. Zona Sur|Lomas de Zamora|San José|', '|Argentina|Bs.As. G.B.A. Zona Sur|Almirante Brown|San Jose|']
['|Argentina|Bs.As. G.B.A. Zona Norte|San Isidro|', '|Argentina|Bs.As. G.B.A. Zona Norte|San Isidro|San Isidro|']
['|Argentina|Buenos Aires Interior|San Antonio de Areco|San Antonio de Areco|', '|Argentina|Buenos Aires Interior|San Antonio de Areco|']
['|Argentina|Buenos Aires Interior|San Andrés de Giles|', '|Argentina|Buenos Aires Interior|San Andrés de Giles|San Andrés de Giles|']
['|Argentina|

Al comparar los elementos de las 40 listas entre sí, vemos que en realidad refieren a la misma localidad*


Hay 4 excepciones:
1. Don Bosco
2. Centro y Microcentro
3. Malvinas Argentinas
4. Los barrios sin especificar dentro de Provincia de bsas

Estas 4 excepciones fueron las que normalizamos en las otras dos columnas previamente.

📌 **Con lo cual, con *place_name* más *state_name* es suficiente para identificar cada localidad, y podemos prescindir de *place_with_parent_names* para construir el modelo.**

*San José pertenece a Alte. Brown y a Lomas de Zamora
Gerli pertenece a Avellaneda y a Lanús.

----

Nos quedaría hacer una última comprobación, que es ver si existen localidades asociadas a más de un ID (es decir la relación inversa a las anteriores). Vemos que hay 32 barrios que están asociados a más de un geo ID.

In [275]:
geoids_by_place_name = data_geonames.groupby(["place_name"])["geonames_id"].nunique().sort_values(ascending = False)
geoids_by_place_name

mask_geoids_by_place_name = geoids_by_place_name > 1
place_name_multi_id = geoids_by_place_name[mask_geoids_by_place_name]
print(place_name_multi_id)
print("Cantidad geo ids con más de una state: ", len(geoids_by_place_name[mask_geoids_by_place_name]))

place_name
San Vicente            3
San Roque              2
Mendoza                2
San Lorenzo            2
San Justo              2
Olavarría              2
San Juan               2
Neuquén                2
Avellaneda             2
Villa Urquiza          2
San José               2
Corrientes             2
Miramar                2
Merlo                  2
Villa Nueva            2
Córdoba                2
Villa Elisa            2
Caseros                2
Ituzaingó              2
Victoria               2
Salta                  2
Rawson                 2
Veinticinco de Mayo    2
Bella Vista            2
La Paz                 2
La Rioja               2
San Luis               2
San Javier             2
Rivadavia              2
Pilar                  2
Santa Fe               2
Santa María            2
Name: geonames_id, dtype: int64
Cantidad geo ids con más de una state:  32


Chequeamos si estos barrios son localidades distintas pero homónimas, sumando la info de state_name.

In [276]:
indices3 = place_name_multi_id.index #nos quedamos con los índices para crear una máscara
mask_indices3 = data_geonames_notnull["place_name"].isin(indices3)
data_geonames_multi_id = data_geonames_notnull.loc[mask_indices3]

geoids_by_place_name = data_geonames_multi_id.groupby("place_name").agg({'geonames_id': 'unique', 'state_name': 'unique', 'place_with_parent_names': 'unique'}).reset_index()
geoids_by_place_name

place_name                        geonames_id  \
0            Avellaneda             [3436227.0, 3436230.0]   
1           Bella Vista             [3436061.0, 3436058.0]   
2               Caseros             [3862356.0, 3435612.0]   
3            Corrientes             [3435217.0, 3435214.0]   
4               Córdoba             [3860259.0, 3860255.0]   
5             Ituzaingó             [3433359.0, 3433357.0]   
6                La Paz             [3849517.0, 3432077.0]   
7              La Rioja             [3848949.0, 3848950.0]   
8               Mendoza             [3844421.0, 3844419.0]   
9                 Merlo             [3844377.0, 3430696.0]   
10              Miramar             [3430668.0, 3844159.0]   
11              Neuquén             [3843123.0, 3843122.0]   
12            Olavarría             [3842670.0, 3842669.0]   
13                Pilar             [3429979.0, 3841149.0]   
14               Rawson             [3839304.0, 3839303.0]   
15            Rivadavia             [3838750.0, 3838749.0]   
16                Salta             [3838233.0, 3838231.0]   
17           San Javier             [3428973.0, 3428974.0]   
18             San José             [3433947.0, 3428927.0]   
19             San Juan             [3837152.0, 3837213.0]   
20            San Justo             [3428775.0, 3837122.0]   
21          San Lorenzo             [3837090.0, 3837098.0]   
22             San Luis             [3837056.0, 3837029.0]   
23            San Roque             [3836587.0, 3836586.0]   
24          San Vicente  [3428056.0, 3835760.0, 3835759.0]   
25             Santa Fe             [3836277.0, 3836276.0]   
26          Santa María             [3836128.0, 3836129.0]   
27  Veinticinco de Mayo             [3833100.0, 3427535.0]   
28             Victoria             [3427500.0, 3832932.0]   
29          Villa Elisa             [3427442.0, 3427443.0]   
30          Villa Nueva             [3832661.0, 3832662.0]   
31        Villa Urquiza             [3433775.0, 3832603.0]   

                                 state_name  \
0        [Bs.As. G.B.A. Zona Sur, Santa Fe]   
1    [Bs.As. G.B.A. Zona Norte, Corrientes]   
2    [Bs.As. G.B.A. Zona Oeste, Entre Ríos]   
3                              [Corrientes]   
4                                 [Córdoba]   
5    [Bs.As. G.B.A. Zona Oeste, Corrientes]   
6                     [Córdoba, Entre Ríos]   
7                                [La Rioja]   
8                                 [Mendoza]   
9      [San Luis, Bs.As. G.B.A. Zona Oeste]   
10  [Buenos Aires Costa Atlántica, Córdoba]   
11                                [Neuquén]   
12                  [Buenos Aires Interior]   
13      [Bs.As. G.B.A. Zona Norte, Córdoba]   
14                       [San Juan, Chubut]   
15                      [San Juan, Mendoza]   
16                                  [Salta]   
17                     [Santa Fe, Misiones]   
18     [Entre Ríos, Bs.As. G.B.A. Zona Sur]   
19                               [San Juan]   
20     [Bs.As. G.B.A. Zona Oeste, Santa Fe]   
21                      [Santa Fe, Córdoba]   
22                               [San Luis]   
23                       [Córdoba, Mendoza]   
24        [Bs.As. G.B.A. Zona Sur, Córdoba]   
25                               [Santa Fe]   
26                     [Córdoba, Catamarca]   
27        [Buenos Aires Interior, Misiones]   
28   [Bs.As. G.B.A. Zona Norte, Entre Ríos]   
29     [Bs.As. G.B.A. Zona Sur, Entre Ríos]   
30                       [Mendoza, Córdoba]   
31            [Capital Federal, Entre Ríos]   

                              place_with_parent_names  
0   [|Argentina|Bs.As. G.B.A. Zona Sur|Avellaneda|...  
1   [|Argentina|Bs.As. G.B.A. Zona Norte|San Migue...  
2   [|Argentina|Bs.As. G.B.A. Zona Oeste|Tres de F...  
3   [|Argentina|Corrientes|Corrientes|, |Argentina...  
4   [|Argentina|Córdoba|Córdoba|, |Argentina|Córdo...  
5   [|Argentina|Bs.As. G.B.A. Zona Oeste|Ituzaingó...  
6   [|Argentina|Córdob

En esta salida vemos que hay casos variados. 

✔️ En 21 casos, la cantidad de ID's coincide con la cantidad de states, con lo cual, inferimos que efectivamente son localidades con el mismo nombre, pero en diferentes regiones.

In [277]:
result = 0
for index, row in geoids_by_place_name.iterrows():
    if len(row["geonames_id"]) == len(row["state_name"]):
        result += 1
print(result)  

21


Nos quedan los 11 casos restantes. Como en la mayoría coincide el *place_name* con el *state_name*, al haber 2 ids, asumimos que uno refiere a la ciudad y otro a la provincia, y **no se trata de un error.** (otro criterio que se podría tomar es asignar el valor de geoname_id correspondiente a la localidad).

In [278]:
result_2 = 0
for index, row in geoids_by_place_name.iterrows():
    if len(row["geonames_id"]) != len(row["state_name"]):
        result_2 += 1
        print (index, row["place_name"],row["state_name"])
print("Cantidad de casos: ", result_2)  

3 Corrientes ['Corrientes']
4 Córdoba ['Córdoba']
7 La Rioja ['La Rioja']
8 Mendoza ['Mendoza']
11 Neuquén ['Neuquén']
12 Olavarría ['Buenos Aires Interior']
16 Salta ['Salta']
19 San Juan ['San Juan']
22 San Luis ['San Luis']
24 San Vicente ['Bs.As. G.B.A. Zona Sur' 'Córdoba']
25 Santa Fe ['Santa Fe']
Cantidad de casos:  11


Resta analizar solo dos casos: Olavarría y San Vicente.

1. San vicente. Vemos que hay 3 ids posibles pero solo dos valores de *state_name*, y por lo tanto solo dos localidades. 

In [279]:
mask_sanvicente = data["place_name"] == "San Vicente"
data_sanvicente = data.loc[mask_sanvicente,["geonames_id","place_name","state_name","country_name","place_with_parent_names"]]
data_sanvicente["geonames_id"].value_counts()

3428056.0    95
3835759.0    13
3835760.0     3
Name: geonames_id, dtype: int64

In [280]:
#San Vicente - valores unicos de state_name por cada ID.
mask_3428056 = data["geonames_id"] == 3428056.0 
data_3428056 = data.loc[mask_3428056,["geonames_id","place_name","place_with_parent_names","state_name","title","description","lat"]]
print(data_3428056["state_name"].unique())
mask_3835759 = data["geonames_id"] == 3835759.0
data_3835759 = data.loc[mask_3835759,["geonames_id","place_name","place_with_parent_names","state_name","title","description","lat"]]
print(data_3835759["state_name"].unique())
mask_3835760 = data["geonames_id"] == 3835760.0
data_3835760= data.loc[mask_3835760,["geonames_id","place_name","place_with_parent_names","state_name","title","description","lat"]]
print(data_3835760["state_name"].unique())

['Bs.As. G.B.A. Zona Sur']
['Bs.As. G.B.A. Zona Sur']
['Córdoba']


Como los dos primeros ID refieren a la misma localidad, nos quedamos con uno solo. Según https://www.geonames.org/3428056/partido-de-san-vicente.html, el correcto es 
3428056.0

In [281]:
#lo aplicamos al df original
data.loc[mask_3835759,"geonames_id_new"] = 3428056.0 #valor de centro de mdq
data.loc[mask_3835759, ["place_name","geonames_id","state_name"
                            ,"place_name_new","geonames_id_new"]]

place_name  geonames_id              state_name place_name_new  \
27393  San Vicente    3835759.0  Bs.As. G.B.A. Zona Sur    San Vicente   
27950  San Vicente    3835759.0  Bs.As. G.B.A. Zona Sur    San Vicente   
30517  San Vicente    3835759.0  Bs.As. G.B.A. Zona Sur    San Vicente   
33045  San Vicente    3835759.0  Bs.As. G.B.A. Zona Sur    San Vicente   
36335  San Vicente    3835759.0  Bs.As. G.B.A. Zona Sur    San Vicente   
38015  San Vicente    3835759.0  Bs.As. G.B.A. Zona Sur    San Vicente   
44701  San Vicente    3835759.0  Bs.As. G.B.A. Zona Sur    San Vicente   
48104  San Vicente    3835759.0  Bs.As. G.B.A. Zona Sur    San Vicente   
48259  San Vicente    3835759.0  Bs.As. G.B.A. Zona Sur    San Vicente   
63233  San Vicente    3835759.0  Bs.As. G.B.A. Zona Sur    San Vicente   
77509  San Vicente    3835759.0  Bs.As. G.B.A. Zona Sur    San Vicente   
80344  San Vicente    3835759.0  Bs.As. G.B.A. Zona Sur    San Vicente   
94099  San Vicente    3835759.0  Bs.As. G.B.A. Zona Sur    San Vicente   

       geonames_id_new  
27393        3428056.0  
27950        3428056.0  
30517        3428056.0  
33045        3428056.0  
36335        3428056.0  
38015        3428056.0  
44701        3428056.0  
48104        3428056.0  
48259        3428056.0  
63233        3428056.0  
77509        3428056.0  
80344        3428056.0  
94099        3428056.0

2. Olavarría. Vemos que hay 2 ids posibles pero un solo state: 

In [282]:
mask_olavarria = data["place_name"] == "Olavarría"
data_olavarria = data.loc[mask_olavarria,["geonames_id","place_name","state_name","country_name","place_with_parent_names"]]
data_olavarria["geonames_id"].value_counts()

3842669.0    5
3842670.0    4
Name: geonames_id, dtype: int64

In [283]:
mask_3842669 = data["geonames_id"] == 3842669.0
data_3842669 = data.loc[mask_3842669,["geonames_id","place_name","place_with_parent_names","state_name","title","description","lat"]]
print(data_3842669["state_name"].unique())
mask_3842670 = data["geonames_id"] == 3842670.0
data_3842670 = data.loc[mask_3842670,["geonames_id","place_name","place_with_parent_names","state_name","title","description","lat"]]
print(data_3842670["state_name"].unique())

['Buenos Aires Interior']
['Buenos Aires Interior']


Nuevamente ambos ID refieren al mismo state, y por lo tanto decidimos quedarnos con el ID 3842669.0, que corresponde al partido de Olavarría según https://www.geonames.org/3842669/partido-de-olavarria.html

In [284]:
#lo aplicamos al df original
data.loc[mask_3842670,"geonames_id_new"] = 3842669.0
data.loc[mask_3842670, ["place_name","geonames_id","state_name"
                            ,"place_name_new","geonames_id_new"]]


place_name  geonames_id             state_name place_name_new  \
7740   Olavarría    3842670.0  Buenos Aires Interior      Olavarría   
7741   Olavarría    3842670.0  Buenos Aires Interior      Olavarría   
12413  Olavarría    3842670.0  Buenos Aires Interior      Olavarría   
51466  Olavarría    3842670.0  Buenos Aires Interior      Olavarría   

       geonames_id_new  
7740         3842669.0  
7741         3842669.0  
12413        3842669.0  
51466        3842669.0

✔️ Con estos análisis, normalizamos los errores y **nos aseguramos que cada ID para representa una localidad única.**

***

Finalizados estos análisis, podríamos intentar recuperar los nulos de *geonames_id* a partir de la información en *place_name* y *state_name*.
Comenzamos recuperando los nulos de *place_name*:

In [285]:
print("Cantidad de nulos en \"place_name\":", data.place_name.isnull().sum())
print("Cantidad barrios: ", len(data.place_name_new.unique()))
print("Cantidad de geo IDS: ", len(data.geonames_id_new.unique()))

Cantidad de nulos en "place_name": 23
Cantidad barrios:  1053
Cantidad de geo IDS:  646


No tenemos los *geoname_id* para estos valores, pero las columnas *title* y *description* nos permiten ver que son casas que están en barrios cerrados en el partido de Tigre.

In [286]:
mask_place_name_null = data.place_name.isnull()
data_null_place_name = data.loc[mask_place_name_null ,["place_name","state_name","place_with_parent_names","geonames_id","title","description"]]
data_null_place_name.head()

place_name                state_name  \
6489         NaN  Bs.As. G.B.A. Zona Norte   
10201        NaN  Bs.As. G.B.A. Zona Norte   
11451        NaN  Bs.As. G.B.A. Zona Norte   
14839        NaN  Bs.As. G.B.A. Zona Norte   
18622        NaN  Bs.As. G.B.A. Zona Norte   

                           place_with_parent_names  geonames_id  \
6489   |Argentina|Bs.As. G.B.A. Zona Norte|Tigre||          NaN   
10201  |Argentina|Bs.As. G.B.A. Zona Norte|Tigre||          NaN   
11451  |Argentina|Bs.As. G.B.A. Zona Norte|Tigre||          NaN   
14839  |Argentina|Bs.As. G.B.A. Zona Norte|Tigre||          NaN   
18622  |Argentina|Bs.As. G.B.A. Zona Norte|Tigre||          NaN   

                                                   title  \
6489               Venta de casa en Santa María de Tigre   
10201  VENTA CASA SANTA MARÍA DE TIGRE COUNTRY BARRIO...   
11451                     SANTA MARIA DE TIGRE IMPECABLE   
14839              Venta de casa en Santa María de Tigre   
18622  Casa con increible vista al lago con playa y m...   

                                             description  
6489   Espectacular casa moderna de una planta, con a...  
10201  Corredor Responsable: SABRINA COCCONI - CSI 62...  
11451  MUY LINDA CASA EN EXCELENTE UBICACION!! Superf...  
14839  Muy linda casa de estilo clásico.-Planta baja;...  
18622   Casa con increible vista al lago con playa de...

In [287]:
data_null_place_name.title.value_counts()

SANTA MARIA DE TIGRE 100                                                               6
Venta de casa en Santa María de Tigre                                                  3
VENTA CASA SANTA MARÍA DE TIGRE COUNTRY BARRIO CERRADO                                 1
SANTA MARIA DE TIGRE IMPECABLE                                                         1
Casa con increible vista al lago con playa y muelle en venta en Sta Maria de Tigre.    1
Venta Casa - Barrio Santa Maria de Tigre                                               1
CASA EN VENTA EN SANTA MARIA DE TIGRE CON RENTA                                        1
Casa (barrio cerrado), Venta                                                           1
Excelente monoambiente. Barrio El Palmar.  Con Renta                                   1
Venta de Casa al rio                                                                   1
Casa en Venta                                                                          1
Santa María de Tigre.

Vemos si hay filas con valor "Tigre" en *place_name*:

In [288]:
mask_tigre = data["place_name_new"] == "Tigre"
data_tigre = data.loc[mask_tigre,["geonames_id","place_name","state_name","title","place_with_parent_names","price_per_m2"]]
print(f"Hay {data_tigre.shape[0]} valores 'Tigre'")

Hay 3324 valores 'Tigre'


Comparamos la media del precio por m2 en ambos grupos, para ver si es razonable asignarles el valor "Tigre a todos" sin importar si están en un barrio cerrado o no, ya que esto suele modificar el precio de las propiedades.

In [289]:
data.loc[mask_place_name_null,"place_name_new"] = "Tigre (Barrio Cerrado)" #asignamos momentáneamente un nuevo valor de place_name para poder agrupar
mask_tigrebc = data["place_name_new"] == "Tigre (Barrio Cerrado)" 
mask_tigres = mask_tigre | mask_tigrebc #hacemos una máscara para juntar ambos valores de Tigre
data_tigres = data.loc[mask_tigres] #creamos un df 
data_tigres.pivot_table(["price_per_m2"], index=["place_name_new"]) #visualizamos la media por cada grupo.

price_per_m2
place_name_new                      
Tigre                    6184.843423
Tigre (Barrio Cerrado)   5458.459683

Como las medias son muy diferentes, dejamos los 2 valores de *place_name* para cada grupo, y creamos un nuevo *geoname_id* para el caso de "Tigre (Barrio Cerrado)" a partir del de "Tigre":

In [290]:
#Le agregamos dos ceros al id original: 3427753.0

data.loc[mask_tigrebc,"geonames_id_new"] = 342775300.0

data.loc[mask_tigrebc, ["place_name","geonames_id","state_name"
                            ,"place_name_new","geonames_id_new"]]


place_name  geonames_id                state_name  \
6489         NaN          NaN  Bs.As. G.B.A. Zona Norte   
10201        NaN          NaN  Bs.As. G.B.A. Zona Norte   
11451        NaN          NaN  Bs.As. G.B.A. Zona Norte   
14839        NaN          NaN  Bs.As. G.B.A. Zona Norte   
18622        NaN          NaN  Bs.As. G.B.A. Zona Norte   
21922        NaN          NaN  Bs.As. G.B.A. Zona Norte   
23664        NaN          NaN  Bs.As. G.B.A. Zona Norte   
24722        NaN          NaN  Bs.As. G.B.A. Zona Norte   
38856        NaN          NaN  Bs.As. G.B.A. Zona Norte   
45970        NaN          NaN  Bs.As. G.B.A. Zona Norte   
46642        NaN          NaN  Bs.As. G.B.A. Zona Norte   
53130        NaN          NaN  Bs.As. G.B.A. Zona Norte   
55306        NaN          NaN  Bs.As. G.B.A. Zona Norte   
57703        NaN          NaN  Bs.As. G.B.A. Zona Norte   
57759        NaN          NaN  Bs.As. G.B.A. Zona Norte   
57764        NaN          NaN  Bs.As. G.B.A. Zona Norte   
57793        NaN          NaN  Bs.As. G.B.A. Zona Norte   
58004        NaN          NaN  Bs.As. G.B.A. Zona Norte   
58037        NaN          NaN  Bs.As. G.B.A. Zona Norte   
59069        NaN          NaN  Bs.As. G.B.A. Zona Norte   
62411        NaN          NaN  Bs.As. G.B.A. Zona Norte   
62413        NaN          NaN  Bs.As. G.B.A. Zona Norte   
63849        NaN          NaN  Bs.As. G.B.A. Zona Norte   

               place_name_new  geonames_id_new  
6489   Tigre (Barrio Cerrado)      342775300.0  
10201  Tigre (Barrio Cerrado)      342775300.0  
11451  Tigre (Barrio Cerrado)      342775300.0  
14839  Tigre (Barrio Cerrado)      342775300.0  
18622  Tigre (Barrio Cerrado)      342775300.0  
21922  Tigre (Barrio Cerrado)      342775300.0  
23664  Tigre (Barrio Cerrado)      342775300.0  
24722  Tigre (Barrio Cerrado)      342775300.0  
38856  Tigre (Barrio Cerrado)      342775300.0  
45970  Tigre (Barrio Cerrado)      342775300.0  
46642  Tigre (Barrio Cerrado)      342775300.0  
53130  Tigre (Barrio Cerrado)      342775300.0  
55306  Tigre (Barrio Cerrado)      342775300.0  
57703  Tigre (Barrio Cerrado)      342775300.0  
57759  Tigre (Barrio Cerrado)      342775300.0  
57764  Tigre (Barrio Cerrado)      342775300.0  
57793  Tigre (Barrio Cerrado)      342775300.0  
58004  Tigre (Barrio Cerrado)      342775300.0  
58037  Tigre (Barrio Cerrado)      342775300.0  
59069  Tigre (Barrio Cerrado)      342775300.0  
62411  Tigre (Barrio Cerrado)      342775300.0  
62413  Tigre (Barrio Cerrado)      342775300.0  
63849  Tigre (Barrio Cerrado)      342775300.0

Por último, vemos que place_name tiene un valor erroneo, mediante un value_counts.

In [291]:
#data.place_name.value_counts().to_csv('place_name_analisis')

Le asignamos el valor de geo id creado recientemente ya que según title, corresponde a un barrio cerrado en el partido de Tigre.

In [292]:
mask_coord_error = data["place_name_new"] == "coordenadas 34.255511"
data_coord_error = data.loc[mask_coord_error,["title","description","geonames_id","place_name","state_name"]]
data_coord_error


data.loc[mask_coord_error,"geonames_id"] = 342775300.0

---

Como último paso, intentamos recuperar los nulos de *geonames_id_new*.

Creamos un nuevo df con las dos variables que nos interesan, pero excluyendo los valores nulos.

In [293]:
mask_geoid_notnull = data.geonames_id_new.notnull()
df_geo_id = data.loc[mask_geoid_notnull,["geonames_id_new","place_name_new","state_name"]]
df_geo_id

geonames_id_new   place_name_new                    state_name
0             3430787.0        Mataderos               Capital Federal
1             3432039.0         La Plata        Bs.As. G.B.A. Zona Sur
2             3430787.0        Mataderos               Capital Federal
3             3431333.0          Liniers               Capital Federal
4             3435548.0           Centro  Buenos Aires Costa Atlántica
...                 ...              ...                           ...
121214        3428983.0       San Isidro      Bs.As. G.B.A. Zona Norte
121215        3436077.0         Belgrano               Capital Federal
121216        3436080.0           Beccar      Bs.As. G.B.A. Zona Norte
121217        3433775.0    Villa Urquiza               Capital Federal
121219        3433955.0  Capital Federal               Capital Federal

[102526 rows x 3 columns]

Ahora eliminamos todos los duplicados de id. Eso nos va a permitir quedarnos con un df que contiene una localidad para cada id. 

In [294]:
df_geo_id_dropdup = df_geo_id.drop_duplicates(subset="geonames_id_new")
print(df_geo_id.shape)
print(df_geo_id_dropdup.shape)
df_geo_id_dropdup

(102526, 3)
(646, 3)


geonames_id_new  place_name_new                    state_name
0             3430787.0       Mataderos               Capital Federal
1             3432039.0        La Plata        Bs.As. G.B.A. Zona Sur
3             3431333.0         Liniers               Capital Federal
4             3435548.0          Centro  Buenos Aires Costa Atlántica
5             3433657.0    Gualeguaychú                    Entre Ríos
...                 ...             ...                           ...
116479        3861887.0           Chaco                         Chaco
117229        3429610.0         Ranchos         Buenos Aires Interior
119567        3854153.0  Hoyo de Epuyén                        Chubut
119657        3850920.0    Laguna Paiva                      Santa Fe
119832        3430940.0       Malabrigo                      Santa Fe

[646 rows x 3 columns]

In [295]:
mapeo = df_geo_id_dropdup.set_index('geonames_id_new')['place_name_new'].to_dict()
#mapeo 

In [296]:
mask_geoidnew_nulls =  data.geonames_id_new.isnull()
data.loc[mask_geoidnew_nulls,"geonames_id_new"] = data["place_name_new"].map(mapeo)

Sin embargo,al verificar la cantidad de nulos, vemos que no se modifica. Por lo que no habría informacion que recuperar, es decir, las localidades presentes en el diccionario ya tenían su geo id asociado:

In [297]:
data.geonames_id_new.isnull().sum()
#data.loc[mask_geoidnew_nulls,["geonames_id_new","place_name_new"]].groupby("place_name_new").agg(list)

18694

#### CONCLUSIÓN 📌 

Decidimos prescindir de *geonames_id_new*, ya que quedó un porcentaje grande de nulos y esa información podemos obtenerla de las combinaciones únicas de *place_name_new* y *state_name*.

## SECCIÓN 2 - INFORMACIÓN DESCRIPTIVA
---

1. floor
2. rooms
3. description
4. title
5. surface_total_in_m2
6. surface_covered_in_m2
7. property_type

In [298]:
data[["floor","rooms","description","title"]].dtypes

floor          float64
rooms          float64
description     object
title           object
dtype: object

#### SECCIÓN 2. 1 - ROOMS

 #### ANÁLISIS 🔎

Analizamos la distribución de los datos, los valores únicos y la cantidad de nulos en *rooms*:

In [299]:
data.rooms.describe() #vemos que la media de habitaciones es cercana a 3 y el desvío, 1.8.

count    47390.000000
mean         3.080840
std          1.860773
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max         32.000000
Name: rooms, dtype: float64

In [300]:
print("Valores únicos en 'rooms': ")
print(data.rooms.value_counts())

Valores únicos en 'rooms': 
3.0     12567
2.0     12433
4.0      7937
1.0      7377
5.0      3782
6.0      1403
7.0       770
8.0       409
10.0      226
9.0       184
11.0       72
12.0       65
13.0       33
14.0       27
15.0       26
17.0       16
16.0       11
20.0       11
22.0        8
18.0        6
21.0        5
19.0        4
30.0        4
25.0        4
32.0        3
23.0        2
24.0        1
31.0        1
29.0        1
27.0        1
28.0        1
Name: rooms, dtype: int64


In [301]:
print("Cantidad de nulos en 'rooms':")
print(data.rooms.isnull().sum())
print("------------------------")
print("Porcentaje de nulos en 'rooms':")
porc_nulos = (data.rooms.isnull().sum() / data.rooms.shape[0] *100).round(2)
print(porc_nulos) 

Cantidad de nulos en 'rooms':
73830
------------------------
Porcentaje de nulos en 'rooms':
60.91



#### Limpieza de Datos 📝

Si bien tenemos un alto porcentaje de nulos, queremos intentar recuperar datos a partir de la información cualitiva de las columnas *title* y description.

Para ello comenzamos haciendo data wrangling sobre *description*.


* **Creamos una nueva columna *description_new***

In [302]:
#Convertimos todos los caracteres a minúsculas para poder aplicar mas fácilmente patrones de búsqueda.
data['description_new'] = data['description'].str.lower()

In [ ]:
#En una lista se almacenan tuplas que contienen todas las posibles variantes de números escritos en palabras, junto con su versión en dígitos. 
#También se incluyen las vocales con y sin tilde.
lista = [('uno', 1), ('dos', 2), ('tres', 3), ('cuatro', 4), ('cinco', 5), ('seis', 6), ('siete', 7), ('ocho', 8), ('nueve', 9), 
         ('monoambiente','1 amb'), ('1er', 1), ('2do', 2), ('3er', 3), ('4to', 4), ('5to', 5), ('6to', 6), ('7mo', 7), ('8vo', 8), ('9no', 9), ('10mo', 10), 
         ('primer', 1), ('primero', 1), ('segundo', 2), ('tercero', 3), ('tercer', 3), ('cuarto', 4), ('quinto', 5), ('sexto', 6), ('séptimo', 7), ('octavo', 8), ('noveno', 9), ('décimo', 10), 
         ('1º', 1), ('2º', 2), ('3º', 3), ('4º', 4), ('5º', 5), ('6º', 6), ('7º', 7), ('8º', 8), ('9º', 9), ('10º', 10),
         ('á', 'a'), ('é', 'e'), ('í', 'i'), ('ó', 'o'), ('ú', 'u')]
#Se define una función que en una columna "key", reemplaza el primer valor de la tupla por el segundo.
def reemplazar_nros_words(df, lista, key):
    for tupla in lista:
        a, b = tupla
        df[key] = df[key].str.replace(a, str(b)) #utilizamos el método .replace

reemplazar_nros_words(data, lista, 'description_new')

In [ ]:
print(data.description_new.head(10)) #Vista rápida a description_new para comprobar el funcionamiento

Una vez arreglada la columna *description*, intentamos extraer información.

* **creamos una nueva columna rooms_new**.

Luego diseñamos una regex para extraer todo lo que nos informe sobre cantidad de rooms.

In [ ]:
data['rooms_new'] = data['rooms']

In [ ]:
#los patrones buscan dormitorios o ambientes, y el/los dígitos asociados.
patron_dorm = "(?P<dormitorios>\d+)\sdorm"
patron_amb = "(?P<ambiente>\d+)\samb"

patron_dorm_compiled = re.compile(patron_dorm)
patron_amb_compiled = re.compile(patron_amb)

A continuación definimos 2 funciones que van a **complementar la aplicación de la regex**.

In [ ]:

def string_to_float_list(lista):      #función que transforma una lista de strings a una lista de floats
    return list(map(float, lista))


def max_list(lista, max_value):       #función que selecciona el valor máximo de una lista, siempre que ese valor sea menor a un umbral definido como max_value
    if not lista:
        return np.NaN
    else:
        valores_permitidos = [x for x in lista if x < max_value]
        return max(valores_permitidos, default = np.NaN)    

A continuación aplicamos las regex. **Tomamos como máximo valor permitido un número de 10 habitaciones**. Todo valor mayor no se utiliza para la imputación.

In [ ]:
lista_new = data.loc[data.rooms.isnull(),'description_new'].apply(lambda x: patron_dorm_compiled.findall(str(x)) #En todas las filas con valor nulo para rooms, se aplican ambas regex
                                                         if patron_dorm_compiled.findall(str(x))                 #si una no obtiene resultado, se pasa a la otra.
                                                         else patron_amb_compiled.findall(str(x)))               #el resultado se guarda en la variable lista_new

data.loc[data.rooms.isnull(),'rooms_new'] = lista_new.apply(lambda x: max_list(string_to_float_list(x), 10)) #se convierte a string la lista obtenida,luego se elige el valor máximo, y se lo aplica a la fila correspondiente
                                                                                                            #en la columna nueva.

✔️ Comparamos los resultados antes y después de aplicar las regex y comprobamos que **disminuyó notablemente la cantidad de nulos**:

In [ ]:
print("Cantidad de nulos en 'rooms':")
print(data.rooms.isnull().sum())
print("Cantidad de nulos en 'rooms_new':")
print(data.rooms_new.isnull().sum())
print("------------------------")
print("Porcentaje de nulos en 'rooms':")
porc_nulos = (data.rooms.isnull().sum() / data.rooms.shape[0] *100).round(2)
print(porc_nulos,"%") 
print("Porcentaje de nulos en 'rooms_new':")
porc_nulos = (data.rooms_new.isnull().sum() / data.rooms_new.shape[0] *100).round(2)
print(porc_nulos,"%") 

A continuación verificamos si hay filas que hayan obtenido el valor 0. 

In [ ]:
print(data.loc[data.rooms_new == 0.0, 'rooms_new'].size)

Dado que son muy pocos valores, los normalizamos imputando la media de la variable:

In [ ]:
mask_valores_validos = data.rooms_new != 0 & data.rooms_new.notnull() #selecciono los valores distintos de 0 y los no nulos para calcular la media
media_rooms_new = data.loc[mask_valores_validos,'rooms_new'].mean().round() #obtengo la media
data.loc[data.rooms_new == 0.0, 'rooms_new'] = media_rooms_new #la imputo a los valores = 0

In [ ]:
# verifico la cantidad de valores con 0 nuevamente
print(data.loc[data.rooms_new == 0.0, 'rooms_new'].sum())

In [ ]:
#Visualizamos rápidamente ambas columnas para verificar que realizó la imputación.
print(data.loc[data.rooms.isnull(), ['rooms', 'rooms_new']])

----

Aún tenemos un 17% de nulos. Para recuperar aún mas información, seguimos los mismos pasos pero utilizando la columna *title*. Además, se completan los valores faltantes (2) de la columna 'description_new' con la columna 'title_new', ya que suelen presentar información similar. 



In [ ]:
data['title_new'] = data['title'].str.lower()

# Se termina la limpieza de la columna de 'description_new'
data.loc[data.description_new.isnull(), 'description_new'] = data.title_new 

In [ ]:
data.description_new.isnull().sum() # se verifica que ya no se tengan mas valores nulos

In [ ]:
reemplazar_nros_words(data, lista, 'title_new') # aplicamos la funcion definida previamente

In [ ]:
lista_new = data.loc[data.rooms.isnull(),'title_new'].apply(lambda x: patron_dorm_compiled.findall(str(x)) 
                                                         if patron_dorm_compiled.findall(str(x)) 
                                                         else patron_amb_compiled.findall(str(x)))

data.loc[data.rooms_new.isnull(),'rooms_new'] = lista_new.apply(lambda x: max_list(string_to_float_list(x), 4)) # Nuevamente usamos un max_value = 10 

✔️ Vemos que los nulos disminuyeron un poco más, de 20.962 a 19.053:

In [ ]:
print(data.rooms.isnull().sum())
print(data.rooms_new.isnull().sum())

---


📌 Para terminar de limpiar la columna, decidimos hacer una **imputación por la media de la variable**. Sin embargo, segmentamos la media agrupando por tipo de propiedad, para ser más precisos.

Creamos una nueva property_type_new, que aunque no es necesario utilizarla en este momento, se integrará al dataset final posteriormente.

In [ ]:
data["property_type_new"] = data["property_type"]

Usamos un group by para ver la cantidad media de habitaciones según propiedad:

In [ ]:

media_x_property_type = data.loc[:, ['property_type','rooms_new']].groupby(['property_type']).mean().round() #agrupamos por tipo de propiedados y aplicamos la media
media_x_property_type = data.loc[:, ['property_type','rooms_new']].groupby(['property_type']).mean().round()
print(media_x_property_type)


In [ ]:
property_type_media_dict = media_x_property_type.to_dict()['rooms_new']  # convertimos el df resultante en un diccionario
print(property_type_media_dict)

for key in property_type_media_dict:  #definimos un ciclo para recorrer los valores nulos restantes, y aplicarles la media según su property type.
    data.loc[data.rooms_new.isnull() & (data.property_type == key), 'rooms_new'] = property_type_media_dict[key]
    

✔️ Verificamos que la columna *rooms* **ya no tiene valos nulos**.

In [ ]:
print("Cantidad de nulos en 'rooms':")
print(data.rooms.isnull().sum())
print("Cantidad de nulos en 'rooms_new':")
print(data.rooms_new.isnull().sum())
print("------------------------")
print("Porcentaje de nulos en 'rooms':")
porc_nulos = (data.rooms.isnull().sum() / data.rooms.shape[0] *100).round(2)
print(porc_nulos,"%") 
print("Porcentaje de nulos en 'rooms_new':")
porc_nulos = (data.rooms_new.isnull().sum() / data.rooms_new.shape[0] *100).round(2)
print(porc_nulos,"%") 

In [ ]:
data.rooms_new.describe()

#### SECCIÓN 2. 2 - FLOOR

#### ANÁLISIS 🔎


Analizamos la distribución de los datos, los valores únicos y la cantidad de nulos en *floor*:

In [ ]:
data.floor.describe()

In [ ]:
print("Valores únicos en 'floor': ")
print(data.floor.value_counts())

In [ ]:
print("Cantidad de nulos en 'floor':")
print(data.floor.isnull().sum())
print("------------------------")
print("Porcentaje de nulos en 'floor':")
porc_nulos = (data.floor.isnull().sum() / data.floor.shape[0] *100).round(2)
print(porc_nulos) 

A pesar del muy alto porcentaje de nulos en *floor*, queremos ver si es posible recuperar información, con una estategia similar que para *rooms*, aunque con algunas modificaciones.

Creamos una pivot_table para visualizar la cantidad de valores de floor, la cantidad de nulos y la media de pisos (floor) para cada tipo de propiedad (PH, departamento, casa, tienda).

In [ ]:
data['floor_null'] = data['floor'].isnull()
data['floor_null_property'] = data['floor'].isnull()
data['porc_nulos_x_property'] = (data.floor.isnull().sum() / data.shape[0] *100).round(2)

resultado = data.groupby('property_type').agg({'floor': 'count', 'floor_null': 'sum', 'floor_null_property': 'mean'})
print(resultado)

Analizamos si la columna *description_new* tiene informacion acerca del piso (floor) con el método .contains, para ver si vale la pena utilizar la regex. 

Obtenemos 54376 valores que podrían recuperarse.

In [ ]:
descrnotnull = data.description_new.notnull() #mascara para quitar los valores nulos, para poder aplicar .contain.
description_clean = data.loc[descrnotnull]    #aplicamos la máscara
contains_piso = description_clean.description_new.str.contains('piso')  #nueva mascara con el metodo .contain.
print (description_clean.loc[contains_piso, "description_new"])  #aplicamos la mascara y visualizamos.
print("------------------------------------------------------")
print("Cantidad de valores a recuperar: ", len(description_clean.loc[contains_piso, "description_new"]))

Exportamos estos valores a un csv para poder analizar mejor el contenido:

In [ ]:
#description_clean.loc[contains_piso, "description_new"].to_csv('description_new_analisis')

#### CONCLUSIÓN📌 

A partir de este análisis se decide tomar como criterio que **los valores que encuentre la regex corresponden al número de piso en que se encuentra la propiedad**, y no la cantidad de plantas.

Como paso previo, consideramos que todos los valores de property_type = house están ubicadas en el piso 1. 

#### Limpieza de Datos 📝

* **Creamos una nueva columna floor_new**:

In [ ]:
data['floor_new'] = data['floor']

In [ ]:
data.loc[data.property_type == 'house', 'floor_new'] = 1 #se considera que las casas están en un piso 1

Creamos la regex:

In [ ]:
patron_piso = "(?P<pisos>\d+)\spiso"  #patrón para extraer dígitos antes de la palabra "piso"
patron_piso_compiled = re.compile(patron_piso)

In [ ]:

lista_floor_new = data.loc[data.floor_new.isnull(), 'description_new'].apply(lambda x: patron_piso_compiled.findall(str(x)))

data.loc[data.floor_new.isnull(),'floor_new'] = lista_floor_new.apply(   #Utilizamos las funciones definidas previamente
    lambda x: max_list(string_to_float_list(x), 53)      # se escoge como valor máximo a 52, ya que la torre más alta en BSAS es la torre YPF con 52 pisos.
) 
                                                                                                  

✔️ Comparamos los nulos y vemos que hubo cambios. (No son la misma cantidad que obtuvimos con el método contain, porque aplicamos el valor 1 a los nulos de "House").

In [ ]:
print("Cantidad de nulos en 'floor':")
print(data.floor.isnull().sum())
print("Cantidad de nulos en 'floor_new':")
print(data.floor_new.isnull().sum())
print("------------------------")
print("Porcentaje de nulos en 'floor':")
porc_nulos = (data.floor.isnull().sum() / data.floor.shape[0] *100).round(2)
print(porc_nulos,"%") 
print("Porcentaje de nulos en 'floor_new':")
porc_nulos = (data.floor_new.isnull().sum() / data.floor_new.shape[0] *100).round(2)
print(porc_nulos,"%") 

----------------------

Analizamos si la columna *title_new* tiene informacion acerca del piso (floor) con el método .contains, para ver si vale la pena utilizar la regex. 

Obtenemos 3260 más que podrían recuperarse.

In [ ]:
print(
    data.loc[data.title_new.str.contains('piso'), 'title_new']
)
print("------------------------------------------------------")
print("Cantidad de valores a recuperar: ", len(data.loc[data.title_new.str.contains('piso'), 'title_new']))

Exportamos estos valores a un csv para poder analizar mejor el contenido:

In [ ]:
#data.loc[data.title_new.str.contains('piso'), 'title_new'].to_csv('title_new_analisis')

**Aplicamos la misma regex a *title*:**

In [ ]:
lista_floor_new = data.loc[data.floor_new.isnull(), 'title_new'].apply(lambda x: patron_piso_compiled.findall(str(x)))
data.loc[data.floor_new.isnull(),'floor_new'] = lista_floor_new.apply(lambda x: max_list(string_to_float_list(x), 53))

✔️ Verificamos que los nulos bajaron un poco más.

In [ ]:
print("Cantidad de nulos en 'floor':")
print(data.floor.isnull().sum())
print("Cantidad de nulos en 'floor_new':")
print(data.floor_new.isnull().sum())
print("------------------------")
print("Porcentaje de nulos en 'floor':")
porc_nulos = (data.floor.isnull().sum() / data.floor.shape[0] *100).round(2)
print(porc_nulos,"%") 
print("Porcentaje de nulos en 'floor_new':")
porc_nulos = (data.floor_new.isnull().sum() / data.floor_new.shape[0] *100).round(2)
print(porc_nulos,"%") 

 #### CONCLUSIÓN 📌

**Se decide no seguir trabajando esta columna** ya que no hay otra estrategia razonable para eliminar nulos. Utilizar la media no sería de mucha utilidad, ya que existe una alta dispersión de valores en la variable.


#### SECCION 2.3 - SURFACE_TOTAL_IN_M2 y SURFACE_COVERED_IN_M2 

Vemos el tipo de las columnas:

In [ ]:
data[["surface_total_in_m2","surface_covered_in_m2"]].dtypes

Recordamos la cantidad de nulos:

In [ ]:
data[["surface_total_in_m2","surface_covered_in_m2"]].isnull().sum()

In [ ]:
data[["surface_total_in_m2","surface_covered_in_m2"]].describe()

#### ANÁLISIS 🔎

Analizamos estrategias para rellenar la **superficie total**.

En primer lugar, queremos comprobar si la superficie total suele coincidir con la superficie cubierta, para ver si podemos reemplazar un valor por otro. 

Para ello, excluimos los valores nulos y planteamos un booleano:

In [ ]:
data.loc[(data.surface_total_in_m2.notnull() & #que la sup. total no sea nula
          data.surface_covered_in_m2.notnull()) & #que la sup. cubierta no sea nula
         (data.surface_total_in_m2 == data.surface_covered_in_m2), #que ambos valores sean iguales
         'property_type'].value_counts()

Vemos que hay 24.173 valores que coinciden, sobre un total de 81.892 valores válidos. Es muy poco representativo como para tomar esta estrategia. 

Si lo hacemos específicamente sobre los departamentos (donde es más probable que las superficies coincidan), vemos que tampoco el número es representativo. Tenemos 14.756 casos en los que los valores coinciden, y 31.300 en que no coinciden (siempre cuando contamos con ambos valores):

In [ ]:
data.loc[(data.surface_total_in_m2.notnull() & 
          data.surface_covered_in_m2.notnull()) & 
         (data.surface_total_in_m2 != data.surface_covered_in_m2) & 
         (data.property_type == 'apartment'), #agregamos una condición más al código anterior
         'property_type'].value_counts()

Es decir que sobre 46.056 casos en los que contamos con ambos valores, el porcentaje de los valores que coinciden es del 32% (14.756)

📌 Por lo tanto decidimos **desestimar esta estrategia** para cualquier tipo de propiedad.

#### 📝 Limpieza de Datos 

Definimos barrer nuevamente las columnas *title_new* y *description_new* para extraer información.

* **Creamos una nueva columna **surface_total_in_m2_new**:

In [ ]:
data['surface_total_in_m2_new'] = data.surface_total_in_m2

Aplicamos una regex sobre *description_new* con un nuevo patrón, reutilizando código anterior.

In [ ]:
patron_superficie = "(?P<superficie>\d+)\sm2"
patron_superficie_compiled = re.compile(patron_superficie)

lista_superficie_new = data.loc[data.surface_total_in_m2.isnull(), 'description_new'].apply(lambda x: patron_superficie_compiled.findall(str(x)))

data.loc[data.surface_total_in_m2.isnull(),'surface_total_in_m2_new'] = lista_superficie_new.apply(lambda x: max_list(string_to_float_list(x), 200))

En este caso, planteamos un valor máximo de 200 m2. 

Vemos que los nulos disminuyen.

In [ ]:
print("Cantidad de nulos en 'surface_total_in_m2':")
print(data.surface_total_in_m2.isnull().sum())
print("Cantidad de nulos en 'surface_total_in_m2_new':")
print(data.surface_total_in_m2_new.isnull().sum())
print("------------------------")
print("Porcentaje de nulos en 'surface_total_in_m2':")
porc_nulos = (data.surface_total_in_m2.isnull().sum() / data.surface_total_in_m2.shape[0] *100).round(2)
print(porc_nulos,"%") 
print("Porcentaje de nulos en 'surface_total_in_m2_new':")
porc_nulos = (data.surface_total_in_m2_new.isnull().sum() / data.surface_total_in_m2_new.shape[0] *100).round(2)
print(porc_nulos,"%") 



A continuación, repetimos el procedimiento para *title_new*

In [ ]:
patron_superficie = "(?P<superficie>\d+)\s?m2"
patron_superficie_compiled = re.compile(patron_superficie)

lista_superficie_new = data.loc[data.surface_total_in_m2_new.isnull(), 'title_new'].apply(lambda x: patron_superficie_compiled.findall(str(x)))

data.loc[data.surface_total_in_m2_new.isnull(),'surface_total_in_m2_new'] = lista_superficie_new.apply(lambda x: max_list(string_to_float_list(x), 200))

Verificamos nulos:

In [ ]:
print("Cantidad de nulos en 'surface_total_in_m2':")
print(data.surface_total_in_m2.isnull().sum())
print("Cantidad de nulos en 'surface_total_in_m2_new':")
print(data.surface_total_in_m2_new.isnull().sum())
print("------------------------")
print("Porcentaje de nulos en 'surface_total_in_m2':")
porc_nulos = (data.surface_total_in_m2.isnull().sum() / data.surface_total_in_m2.shape[0] *100).round(2)
print(porc_nulos,"%") 
print("Porcentaje de nulos en 'surface_total_in_m2_new':")
porc_nulos = (data.surface_total_in_m2_new.isnull().sum() / data.surface_total_in_m2_new.shape[0] *100).round(2)
print(porc_nulos,"%") 


Aún tenemos un buen % de nulos, por lo tanto intentamos una estrategia más. Vamos a imputar la media de manera segmentada, es decir, de acuerdo a otras variables.

Pero antes, excluimos ciertos valores que afectan al calculo de la media por ser outliers, y que probablemente sean errores.

Se extrajeron los valores de superficie total a un csv y se evaluó que estos aumentan progresivamente hasta 50.000, donde existe un salto hacia 93.000.

A partir de esto se crea una máscara, y a los valores por encima de 50.000 se los reemplaza momentáneamente por nulos, para tener una media más representativa:

In [ ]:
mask_50000 = data.surface_total_in_m2_new > 50000
data.loc[mask_50000,'surface_total_in_m2_new'] = np.NaN

Luego calculamos las medias con una pivot_table y vemos que la pivot_table que surge de *surface_total_in_m2_new* efectivamente tiene valores más bajos. 

In [ ]:
print(data.pivot_table('surface_total_in_m2' , index = 'property_type'))
print("------------------VS---------------")
print(data.pivot_table('surface_total_in_m2_new' , index = 'property_type'))

Creamos una tabla_pivot que nos muestre la media de la superficie total, agrupando por cantidad de habitaciones y diferenciando por tipo de propiedad. La idea es obtener la media, para poder aplicarla segmentadamente, según estas variables.

In [ ]:
data_pivot_1 = data.pivot_table('surface_total_in_m2' , index = 'rooms_new', columns='property_type')
print(data_pivot_1)

Luego, creamos un ciclo que recorre la tabla pivot, y siempre que el valor de superficie en el df original sea nulo, le aplica la media que le corresponde, según su cantidad de habitaciones y su tipo de propiedad.

In [ ]:
for indice, row in data_pivot_1.iterrows():       
    PH_mean = row['PH']
    apartment_mean = row['apartment']
    house_mean = row['house']
    store_mean = row['store']    
    
    data.loc[(data.surface_total_in_m2_new.isnull()) & (data.rooms_new == indice) &  (data.property_type == 'PH') , 'surface_total_in_m2_new'] = PH_mean
    data.loc[(data.surface_total_in_m2_new.isnull()) & (data.rooms_new == indice) &  (data.property_type == 'apartment'), 'surface_total_in_m2_new'] = apartment_mean
    data.loc[(data.surface_total_in_m2_new.isnull()) & (data.rooms_new == indice) &  (data.property_type == 'house'), 'surface_total_in_m2_new'] = house_mean
    data.loc[(data.surface_total_in_m2_new.isnull())& (data.rooms_new == indice) &  (data.property_type == 'store'), 'surface_total_in_m2_new'] = store_mean

In [ ]:
print("Cantidad de nulos en 'surface_total_in_m2':")
print(data.surface_total_in_m2.isnull().sum())
print("Cantidad de nulos en 'surface_total_in_m2_new':")
print(data.surface_total_in_m2_new.isnull().sum())
print("------------------------")
print("Porcentaje de nulos en 'surface_total_in_m2':")
porc_nulos = (data.surface_total_in_m2.isnull().sum() / data.surface_total_in_m2.shape[0] *100).round(2)
print(porc_nulos,"%") 
print("Porcentaje de nulos en 'surface_total_in_m2_new':")
porc_nulos = (data.surface_total_in_m2_new.isnull().sum() / data.surface_total_in_m2_new.shape[0] *100).round(2)
print(porc_nulos,"%") 

✔️ Con esta estrategia dejamos la variable prácticamente libre de nulos. 

#### CONCLUSIÓN 📌

Dado que *surface_covered_in_m2* es la superficie cubierta de las propiedades, y que estaría contenida en la superficie total, decidimos **obviar esta variable y trabajar solo con *surface_total_in_m2_new* a la hora de predecir el precio**

----------

## SECCIÓN 3 - VALORES


1. currency   
2. price
3. price_aprox_local_currency    
3. price_aprox_usd
4. price_usd_per_m2             
5. price_per_m2                



In [ ]:
data.columns

In [ ]:
data_valores = data.iloc[:,[11,12,13,14,17,18]]   
data_valores.head(10)

#### SECCION 3.1 - CURRENCY (UNIFICACIÓN A DOLARES (USD))


#### ANÁLISIS 🔎

In [ ]:
print("Cantidad de nulos en currency:")
print(data.currency.isnull().sum())
print("------------------------")
print("Porcentaje de nulos en currency:")
porc_nulos = (data.currency.isnull().sum() / data_geo.shape[0] *100).round(2)
print(porc_nulos)

In [ ]:
data.currency.value_counts()

Queremos comprobar que cuando *currency* es nulo, todas las columnas relativas a precio también son nulas y por lo tanto no podemos obtener información de ellas. 
Vemos que para todas las filas menos 1, no hay ningún valor relativo a precio.

In [ ]:
mask_cur_null = data.currency.isnull()
comprobacion_nulos = data.loc[mask_cur_null,["currency","price_aprox_usd","price_aprox_local_currency","price","price_usd_per_m2","price_per_m2"]]

#print(comprobacion_nulos)
print(comprobacion_nulos.isnull().sum(axis=1).value_counts())

#### 📝 Limpieza de Datos 

* **Creamos las columnas nuevas _new**

In [ ]:
data["currency_new"] = data.currency
data["price_new"] = data.price
data["price_aprox_usd_new"] = data.price_aprox_usd

Armamos un df reducido en donde extraemos los campos necesarios para el análisis de precios:

In [ ]:
dataframe_prices=data.loc[:, ['property_type','price', 'currency', 'price_aprox_local_currency','price_aprox_usd','surface_total_in_m2','surface_total_in_m2_new','surface_covered_in_m2','price_usd_per_m2','price_per_m2','rooms','surface_total_in_m2_new']]
dataframe_prices.head(3)

Creamos un dataframe con las columnas donde *currency* sea ARS y el precio no sea null

In [ ]:
data_ars_mask=(dataframe_prices.currency=='ARS')&(dataframe_prices.price.notnull())&(dataframe_prices.price_aprox_usd.notnull())
data_ars=dataframe_prices[data_ars_mask]
data_ars.head(3)

Al dataframe auxiliar le creamos un campo price_new para asignar directamente el valor de price_aprox_usd. Y en *currency_new* asignamos "USD"

In [ ]:
data_ars['price_new']=data_ars['price_aprox_usd'] # igualamos price_aprox_usd con price_new

In [ ]:
data_ars['currency_new']='USD' # cambiamos la moneda a dolares
data_ars.head(3)

In [ ]:
#Creamos una máscara para extraer los registros con moneda en dólares y además los campos
#que corresponden para el análisis
mask_currency_usd = data['currency'] == 'USD'
data_currency_usd = data.loc[mask_currency_usd, ['place_name', 'price', 'currency', 'price_aprox_local_currency', 'price_aprox_usd']]
data_currency_usd.sample(5)

* Encontramos con este proceso la relación que existe entre la columna price y price_aprox_local_currency


In [ ]:
#sumamos las columnas price y price_aprox_local_currency del dataset original
sum_price = np.sum(data_currency_usd['price'])
sum_price_aprox_local = np.sum(data_currency_usd['price_aprox_local_currency'])

* Dividimos la sumatoria entre la sumatoria de price y price_aprox_local_currency

In [ ]:
proporcion_dolar_pesos =  np.round((sum_price_aprox_local / sum_price), 4)

* Podemos verificar que existe el factor de proporcion 17.6445

In [ ]:
proporcion_dolar_pesos

* Con este factor de proporción obtenido de 17.6445 podemos multiplicar la columna price proporcion_dolar_pesos y es igual a la columna price_aprox_local_currency, que será empleado cuando se haga el análisis de la columna price_aprox_local_currency más adelante.

Comprobamos que *price_aprox_local_currency* es equivalente a lo que se encuentra almacenado en esa columna actualmente. 
Con el nuevo precio que está guardado.
En *price_new* se va a multiplicar por 17.6445 y obtenemos la columna *calculo_price_local_currency*

In [ ]:

df_local_currency=data_ars.loc[(data_ars.price_new.notnull())&(data_ars.price_aprox_usd.notnull())]
df_local_currency['calculo_price_local_currency']=df_local_currency.loc[:,'price_new']*proporcion_dolar_pesos
df_local_currency.head(3)

Filtramos para ver si hay alguna diferencia entre lo que calculamos y lo que tenemos almacenado en *price_aprox_local_currency* actualmente, y podemos observar que no hay ninguna diferencia, por lo tanto **podemos reemplazar *price* con el valor de *price_aprox_usd* y además cambiar la columna currency a USD:

In [ ]:

df_local_currency['diferencia_calculo']=df_local_currency['price_aprox_local_currency']-df_local_currency['calculo_price_local_currency']
print(df_local_currency[df_local_currency.diferencia_calculo>0])

#### 📝 Limpieza de Datos 

Se extraen los registros en donde la moneda es ARS, el *price* no es null y el *price_aprox_usd* no es null

In [ ]:
data_currency_ars_mask=(data.currency_new=='ARS')&(data.price_new.notnull())&(data.price_aprox_usd_new.notnull())
data_currency_ars=data[data_currency_ars_mask]
data_currency_ars.head(3)

En base al análisis realizado, se cambia la columna currency_new de ARS a USD y el precio_new reemplazamos por lo que el valor que tenemos
guardado en price_aprox_usd, con el objetivo de tener todo el dataset en una única moneda

* A continuacion se eliminan los registros con currency 'PEN' Y 'UYU', los mismos suman la totalidad de 3 registros, son considerados outliers

In [ ]:
data.loc[data_currency_ars_mask,'price_new'] = data.loc[data_currency_ars_mask,'price_aprox_usd']
data.loc[data_currency_ars_mask,'currency_new']='USD'

In [ ]:
indices_pen_uyu = data[(data.currency_new == 'PEN') | (data.currency_new == 'UYU')].index
data.drop(indices_pen_uyu, inplace=True)

------------------------------------------------

#### SECCION 3.2 - COLUMNA PRICE

#### 📝 Limpieza de Datos 

In [ ]:
data.price_new.describe()

In [ ]:
data.price_new.isnull().sum()

#### 📝 Limpieza de Datos 

Para recuperar los nulos en *price*, se decide hacer una imputacion de la media del precio según la zona geográfica. 

In [ ]:
pivot_table_prices_avg = data.pivot_table('price_new', index = ['state_name','place_name_new'])
pivot_table_prices_avg

In [ ]:
# Se recorre la pivot table para poder asignar la media por provincia y por ciudad, se asgina la media a 'price_new', 'price_aprox_usd_new', y se pasa a dolares la currency_new cuando es nula
for indice, row in pivot_table_prices_avg.iterrows():
    provincia, ciudad = indice     
    data.loc[(data.currency.isnull()) & (data.price.isnull()) & (data.state_name==provincia) & (data.place_name_new==ciudad), ['price_new', 'price_aprox_usd_new']] = row['price_new']    
    data.loc[(data.currency.isnull()) & (data.price.isnull()) & (data.state_name==provincia) & (data.place_name_new==ciudad), 'currency_new'] =  'USD'

A continuación vemos como se modificaron los nulos en las 3 columnas afectadas:

In [ ]:
print(data.currency.isnull().sum())
print(data.currency_new.isnull().sum())

In [ ]:
print(data.price.isnull().sum())
print(data.price_new.isnull().sum())

In [ ]:
print(data.price_aprox_usd.isnull().sum())
print(data.price_aprox_usd_new.isnull().sum())

----------------------------------------------------------------------------------

#### SECCION 3.3 - PRICE_APROX_LOCAL_CURRENCY

Queremos verificar de donde sale el valor de esta variable, y si tiene relación con la variable price (price_new). Para esto vamos a crear un dataframe auxiliar:

In [ ]:
df_price_to_price_local_currency=dataframe_prices.loc[(dataframe_prices.price.notnull())&(dataframe_prices.price_aprox_usd.notnull())&(dataframe_prices.currency=='USD')]
df_price_to_price_local_currency.head(3)

Verificamos que multiplicando price*17,6445 nos da como resultado la columna *price_aprox_local_currency*

In [ ]:
df_price_to_price_local_currency['calculo_price_local_currency']=df_price_to_price_local_currency.loc[:,'price']*proporcion_dolar_pesos
df_price_to_price_local_currency.head(3)

✔️ A continuación, en la columna *diferencia_calculo* podemos observar que es 0 en todos los registros, por lo tanto se concluye que se puede aplicar la formula *price x proporcion_dolar_pesos* para poblar *price_aprox_local_currency*, cuando currency es USD:

In [ ]:
df_price_to_price_local_currency['diferencia_calculo']=df_price_to_price_local_currency['price_aprox_local_currency']-df_price_to_price_local_currency['calculo_price_local_currency']
print(df_price_to_price_local_currency[df_price_to_price_local_currency.diferencia_calculo>0])

#### 📝 Limpieza de Datos 

* **Creamos una variable *price_aprox_local_currency_new* para proceder a poblar con los nuevos datos**

In [ ]:
data['price_aprox_local_currency_new']=data.price_aprox_local_currency

In [ ]:
#Aqui se verifica que la columna price_new sea mayor a 0, que price_aprox_local_currency_new sea null y que la moneda sea igual a 'USD'

price_local_currency_mask=(data.price_new.notnull())&(data.price_aprox_local_currency_new.isnull())&(data.currency_new=='USD')&(data.price_new>0)



Aplicamos el calculo:

In [ ]:
#procedemos a poblar el campo price_aprox_local_currency con la siguiente formula: price x 17.644
data.loc[price_local_currency_mask,'price_aprox_local_currency_new'] = data.loc[price_local_currency_mask,'price_new']*proporcion_dolar_pesos

✔️ Y verificamos que la cantidad de nulos corresponde con la cantidad que teníamos en las variables previamente modificadas. 

In [ ]:
data.price_aprox_local_currency_new.isnull().sum()

-----------------------------------------------------

#### SECCION 3.4 - PRICE_APROX_USD

#### ANÁLISIS 🔎

A continuación, queremos verificar que si el campo *currency* es USD, la columna *price* y *price_aprox_usd* tienen el mismo valor.

In [ ]:
series_prices=data.loc[:, ['property_type','price', 'currency', 'price_aprox_local_currency','price_aprox_usd','surface_total_in_m2','surface_total_in_m2_new','surface_covered_in_m2','price_usd_per_m2','price_per_m2','rooms','surface_total_in_m2_new']]

Creamos una columna diferencia_price_aprox_usd con la diferencia entre la columna price y price_prox_usd 

In [ ]:
price_aprox_usd_mask=(series_prices.price.notnull())&(series_prices.price_aprox_usd.notnull()&(series_prices.price>0)&(series_prices.currency=='USD'))
serie_price_aprox_usd=series_prices.loc[price_aprox_usd_mask]
serie_price_aprox_usd['diferencia_price_aprox_usd']=serie_price_aprox_usd['price']-serie_price_aprox_usd['price_aprox_usd']

La diferencia en la columna *diferencia_price_aprox_usd* es 0, por lo tanto, cuando la moneda es USD la columna *price* y *price_aprox_usd* son iguales.

In [ ]:
print('<----------------------------------------------->')
print("Numero de registros que tienen diferencia mayor a 0:")
print(serie_price_aprox_usd[serie_price_aprox_usd.diferencia_price_aprox_usd>0])

#### 📝 Limpieza de Datos 

Procedemos a rellenar la variable según el criterio obtenido:

In [ ]:
#Aqui se verifica que la columna price_new sea mayor a 0, que price_aprox_usd_new sea null y que la currency_new sea igual a 'USD'
price_aprox_usd_mask=(data.price_new.notnull())&(data.price_aprox_usd_new.isnull())&(data.currency_new=='USD')&(data.price_new>0)

In [ ]:
#Igualamos al campo price.
data.loc[price_aprox_usd_mask,'price_aprox_usd_new'] = data.loc[price_aprox_usd_mask,'price_new']

In [ ]:
data.price_aprox_usd_new.isnull().sum()

-----------------------------------------------------

#### SECCION 3.5 - PRICE_USD_PER_M2 y PRICE_PER_M2 

#### ANÁLISIS 🔎

In [ ]:
series_prices.isnull().sum()

Queremos verificar la hipótesis de que*price_usd_per_m2* es la división *price_aprox_usd*/*surface_total_in_m2*. Para ello creamos una nueva columna con el resultado de esa división y la comparamos con la columna original.

In [ ]:
#creamos un df excluyendo los nulos en ambos tipos de superficie y en price.
series_prices_not_null=series_prices.loc[(series_prices.price_aprox_usd.notnull())
                                         &(series_prices.surface_total_in_m2.notnull())
                                         &(series_prices.surface_covered_in_m2.notnull())]
series_prices_not_null.head(10)

Creamos una columna adicional para verificar que price_aprox_usd/surface_total_in_m2 = price_usd_per_m2

In [ ]:

series_prices_not_null['calculo_price_usd_per_m2']=series_prices_not_null['price_aprox_usd']/series_prices_not_null['surface_total_in_m2']
series_prices_not_null

✔️ A continuación, en la columna *diferencia_price_usd_per_m2* podemos observar que la misma es mínima, por lo tanto se concluye que se puede
aplicar la formula anterior para poblar la *columna price_usd_per_m2*:

In [ ]:







serie_dif=series_prices_not_null[(series_prices_not_null['calculo_price_usd_per_m2']-series_prices_not_null['price_usd_per_m2'])>0]
serie_dif['diferencia_price_usd_per_m2']=serie_dif['calculo_price_usd_per_m2'].astype(float)-serie_dif['price_usd_per_m2'].astype(float)
serie_dif

--------------------------------------

De forma análoga, También verificamos si  *price_per_m2* es igual a la división *price_aprox_usd/surface_covered_in_m2*

In [ ]:
series_prices_not_null['calculo_price_per_m2']=series_prices_not_null['price_aprox_usd']/series_prices_not_null['surface_covered_in_m2']

In [ ]:
serie_dif_price_m2=series_prices_not_null[(series_prices_not_null['calculo_price_per_m2']-series_prices_not_null['price_per_m2'])>0]
serie_dif_price_m2['diferencia_price_m2']=serie_dif_price_m2['calculo_price_per_m2'].astype(float)-serie_dif_price_m2['price_per_m2'].astype(float)
serie_dif_price_m2

En la columna diferencia_price_m2 podemos observar nuevamente que la diferencia es mínima, por lo tanto se concluye que se puede
aplicar la formula price_aprox_usd/surface_covered_in_m2 para poblar la columna price_per_m2

A continuación, verificamos cuántos registros son nulos en *price_usd_per_m2*, pero que tengan datos en *price_aprox_usd* y en *surface_total_in_m2_new* (y que esta ultima sea > 0). De acuerdo a ello vemos que podríamos recuperar 31788 nulos:

In [ ]:

resultado=data[(data.price_aprox_usd.notnull())&(data.surface_total_in_m2_new.notnull())&(data.surface_total_in_m2_new>0)&(data.price_usd_per_m2.isnull())]
resultado_prices=resultado.loc[:, ['price_usd_per_m2','price','price_aprox_usd','surface_total_in_m2_new']]
print(resultado_prices.shape[0])
resultado_prices


#### 📝 Limpieza de Datos 

A partir de lo verificado previamente, procedemos a llenar los nulos.

* **Creamos una copia exacta de las variables:**

In [ ]:
data['price_usd_per_m2_new']=data.price_usd_per_m2

In [ ]:
data['price_per_m2_new']=data.price_per_m2

In [ ]:
#Aqui se verifica que price_aprox_usd no sea null y que surface_total_in_m2_new sea mayor que 0,

price_usd_per_m2_mask=(data.price_aprox_usd_new.notnull())&(data.surface_total_in_m2_new.notnull())&(data.surface_total_in_m2_new>0)&(data.price_usd_per_m2_new.isnull())
lista_price_usd_per_m2_new=data[price_usd_per_m2_mask]
lista_price_usd_per_m2_new.head(3)

#procedemos a poblar el campo price_usd_per_m2_new con la siguiente formula: price_aprox_usd/surface_total_in_m2_new
data.loc[price_usd_per_m2_mask,'price_usd_per_m2_new'] = data.loc[price_usd_per_m2_mask,'price_aprox_usd_new']/ data.loc[price_usd_per_m2_mask,'surface_total_in_m2_new']


Verificamos la cantidad de nulos y bajaron exactamente la cantidad que podíamos recuperar.

In [ ]:
print("Cantidad de nulos en price_usd_per_m2:")
print(data.price_usd_per_m2.isnull().sum())

print("Porcentaje de nulos enprice_usd_per_m2:")
porc_nulos = (data.price_usd_per_m2.isnull().sum() / data.shape[0] *100).round(2)
print(porc_nulos)
print("------------------------VS----------------------------")
print("Cantidad de nulos en price_usd_per_m2_new:")
print(data.price_usd_per_m2_new.isnull().sum())

print("Porcentaje de nulos en price_usd_per_m2_new:")
porc_nulos = (data.price_usd_per_m2_new.isnull().sum() / data.shape[0] *100).round(2)
print(porc_nulos)


Y a continuación repetimos el procedimiento para *PRICE_PER_M2*.

Creamos una copia exacta para proceder a poblar con los nuevos datos:

In [ ]:
#Aquí se verifica que price_aprox_usd no sea null y que surface_covered_in_m2_new sea mayor que 0,

price_per_m2_mask=(data.price_aprox_usd_new.notnull())&(data.surface_covered_in_m2.notnull())&(data.surface_covered_in_m2>0)&(data.price_per_m2.isnull())

lista_price_per_m2_new=data[price_per_m2_mask]
lista_price_per_m2_new.head(3)

#procedemos a poblar el campo price_per_m2_new con la siguiente formula: price_aprox_usd/surface_covered_in_m2
data.loc[price_per_m2_mask,'price_per_m2_new'] = data.loc[price_per_m2_mask,'price_aprox_usd_new']/ data.loc[price_per_m2_mask,'surface_covered_in_m2']

Y verificamos nulos:

In [ ]:
print("Cantidad de nulos en price_per_m2:")
print(data.price_per_m2.isnull().sum())

print("Porcentaje de nulos en price_per_m2:")
porc_nulos = (data.price_per_m2.isnull().sum() / data.shape[0] *100).round(2)
print(porc_nulos)
print("------------------------VS----------------------------")
print("Cantidad de nulos en price_per_m2_new:")
print(data.price_per_m2_new.isnull().sum())

print("Porcentaje de nulos en price_per_m2_new:")
porc_nulos = (data.price_per_m2_new.isnull().sum() / data.shape[0] *100).round(2)
print(porc_nulos)


## SECCIÓN 4 - DATASET FINAL

Visualizamos como quedaron la cantidad de nulos en el dataset original, que incluye todas las nuevas columnas creadas en la limpieza.

In [ ]:
print(data.isnull().sum())

In [ ]:
data.rename(columns={'surface_covered_in_m2': 'surface_covered_in_m2_new'},inplace=True)
data.columns

In [ ]:
data['intermediate_covered_calculation'] = data.groupby('property_type_new')['surface_covered_in_m2_new'].transform('mean')+ (data.groupby('property_type_new')['surface_total_in_m2_new'].transform('mean') - data.groupby('property_type_new')['surface_covered_in_m2_new'].transform('mean'))

In [ ]:
data['surface_covered_in_m2_new'].fillna(data['intermediate_covered_calculation'], inplace=True)

In [ ]:
print(data.isnull().sum())

**A continuación creamos un nuevo df llamado *data_model* que incluye solo las columnas trabajadas.**
De esta manera ya prescindimos de las 7 columnas mencionadas en el análisis preliminar (Unnamed: 0, Operation, place_with_parent_names, country_name, properati_url, image_thumbnail, expenses) y las 4 columnas que no fueron trabajadas (lat-lon, lat, lon y surface_covered_in_m2).

In [ ]:
data_model = data.filter(like='_new', axis=1)

In [ ]:
print(data_model.shape) #26 columnas - 7 - 4 = 15
data_model .isnull().sum()

#### SECCION 4.1 - ELIMINACIÓN DE COLUMNAS

A continuación prescindimos de aquellas columnas que luego de la limpieza aún tengan gran porcentaje de nulos, o que luego del análisis concluimos que no son importantes para entrenar el modelo. 

1. **'price_per_m2_new' y 'floor_new'**. Aunque se hicieron esfuerzos por llenar los nulos, no pudieron cubrirse todos, y para el analisis dichas columna no influyen significativamente.
2. **'geonames_id_new'**. A pesar del análisis, no se pudieron recuperar todos los nulos. Por otra parte, esa información puede recuperarse de otras columnas ('place_name_new, state_name_new')
3. **'price_aprox_usd_new'** no se toma en cuenta porque es igual a 'price_new', ya que se pasaron todos los valores a dólares

In [ ]:
columnas_a_eliminar = ["price_per_m2_new","floor_new", "geonames_id_new", "price_aprox_usd_new"]
data_model = data_model.drop(columnas_a_eliminar, axis=1)
data_model.shape

#### SECCION 4.2 - ELIMINACIÓN DE REGISTROS

A continuación procedemos a limpiar definititamente los registros que aún tienen nulos en determinadas variables, para poder hacer la martriz de correlación posteriormente. 

1. Registros con nulos en *currency_new*, ya que cuando esta es nula, son nulas todas las columnas referenciales al precio.

In [ ]:
data_model.dropna(subset=['currency_new'], axis=0, inplace=True)

In [ ]:
data_model.isnull().sum()
print(data_model.shape)

2. Registros con nulos en *price_new*. Sin el precio, no se puede realizar correctamente el análisis.

In [ ]:
data_model.dropna(subset=['price_new'], axis=0, inplace=True)
print(data_model.shape)

3. Registros con nulos en la columna 'price_usd_per_m2_new', ya que sin ellos no se puede realizar correctamente el análisis

In [ ]:
data_model.dropna(subset=['price_usd_per_m2_new'], axis=0, inplace=True)
print(data_model.shape)

Verificamos que ahora ninguna columna contiene nulos:

In [ ]:
data_model.isnull().sum()

Y a continuación verificamos cuántos registros pudimos retener del dataset original.

In [ ]:
print(data.shape)
print(data_model.shape)

In [ ]:
print("Porcentaje de registros válidos del modelo actual respecto al anterior:")
print(f"{np.round((data_model.shape[0] / data.shape[0] * 100), 2)} %")

## SECCIÓN 5 - ANÁLISIS DE CORRELACIÓN

En este caso no podemos usar la covarianza para estimar la relación entre variables, ya que tenemos diferentes unidaeddes de medida (m2, dolares, cantidad de rooms, etc). 

Con lo cual estimamos una matriz de correlación.

Para cacular correlaciones no puede haber nulos en las columnas. Seleccionamos solamente las columnas numéricas.

In [ ]:
matrix_corr = data_model[['rooms_new','price_new','surface_total_in_m2_new','price_usd_per_m2_new']].corr().round(3)
matrix_corr

In [ ]:
data_model_graph = data_model.rename(columns={'rooms_new':'Ambientes',
                                   'price_new':'Precio',
                                   'surface_total_in_m2_new':'Superficie total en m2',
                                   'price_usd_per_m2_new':'Precio en dólares por m2'})

In [ ]:
data_model_graph.columns

In [ ]:
matrix_corr_graph = data_model_graph[["Ambientes","Precio","Superficie total en m2","Precio en dólares por m2"]].corr().round(3)
matrix_corr_graph

Vemos que hay una correlaciones bajas por lo general, la correlacion mas alta obtenidad se da entre 'rooms_new' y 'surface_total_in_m2_new'

* Se realiza un grafico para poder verlo con mayor claridad

In [ ]:
plt.figure(figsize=(10, 8))
sns.heatmap(matrix_corr_graph, annot=True, cmap='RdYlGn', fmt='.2f', linewidths=.5)
plt.title('Correlación entre columnas categóricas')
plt.show()

In [ ]:
# Se migra el modelo de datos
data_model.to_csv('properatti_model_data')

In [ ]:
data_model.columns

In [ ]:
data_model.dtypes

In [ ]:
data_model.rooms_new.sort_values(ascending=False)

In [ ]:
data_model.surface_total_in_m2_new.sort_values(ascending=False)

In [ ]:
data_model.price_new.sort_values(ascending=False)

In [ ]:
data_model.describe()

In [ ]:
data_model.dtypes

In [ ]:
data_model.rooms_new = data_model.loc[data_model.rooms_new < 11, 'rooms_new']

In [ ]:
data_model.shape

In [ ]:
data_model = data_model.dropna()

In [ ]:
data_model.shape

# TP 2

## SECCIÓN 5 - ANÁLISIS DE CORRELACIÓN

En este caso no podemos usar la covarianza para estimar la relación entre variables, ya que tenemos diferentes unidaeddes de medida (m2, dolares, cantidad de rooms, etc). 

Con lo cual estimamos una matriz de correlación.

Para cacular correlaciones no puede haber nulos en las columnas. Seleccionamos solamente las columnas numéricas.

In [ ]:
matrix_corr = data_model[['rooms_new','price_new','surface_total_in_m2_new','price_usd_per_m2_new','surface_covered_in_m2_new']].corr().round(3)
matrix_corr

Vemos que hay una correlaciones bajas por lo general, la correlacion mas alta obtenidad se da entre 'rooms_new' y 'surface_total_in_m2_new'

* Se realiza un grafico para poder verlo con mayor claridad

In [ ]:
plt.figure(figsize=(10, 8))
sns.heatmap(matrix_corr, annot=True, cmap='RdYlGn', fmt='.2f', linewidths=.5)
plt.title('Correlación entre columnas categóricas')
plt.show()

### Limpiamos outliers de rooms

In [ ]:
data_model.rooms_new = data_model.loc[data_model.rooms_new < 11, 'rooms_new']

In [ ]:
data_model = data_model.dropna()

### LIMPIEZA DE OUTLIERS. Volvemos a limpiar outliers de las demas variables para evitar fallas en el modelo

In [ ]:
columnas = 'surface_total_in_m2_new', 'price_new', 'price_usd_per_m2_new',"surface_covered_in_m2_new"

for columna in columnas:
    columna_limpia = data_model[columna]

    q1 = columna_limpia.quantile(0.25)
    #print(q1)
    q3 = columna_limpia.quantile(0.75)
    #print(q3)
    iqr = (q3 - q1) * 1.5

    limite_sup = q3 + iqr
    limite_inf = 0
    
    print("Limite sup", columna, limite_sup)
    print("Limite inf", columna, limite_inf)
    
    outlier_mask_up = columna_limpia < limite_sup
    outlier_mask_down = columna_limpia > limite_inf
    outlier_mask = np.logical_and(outlier_mask_up, outlier_mask_down)
    
    data_model = data_model.loc[outlier_mask,:]

print(data_model.shape)
    

In [ ]:
print("Porcentaje de registros válidos del modelo actual respecto al anterior:")
print(f"{np.round((data_model.shape[0] / data.shape[0] * 100), 2)} %")

In [ ]:
cols = 'rooms_new', 'surface_total_in_m2_new', 'price_new', 'price_usd_per_m2_new', "surface_covered_in_m2_new"

for x in cols:
    missing_values = data_model[x].isna().sum()
    print(f"{x}: {missing_values}")    

### SE AGREGAN NUEVAS FEATURES AL MODELO DE DATOS (dummies de variables categoricas)

In [ ]:
dummies_prop_type = pd.get_dummies(data_model.property_type_new, drop_first=True)
data_model_ml = pd.concat([data_model, dummies_prop_type], axis=1)

### Se observan las nuevas variables agregadas en las columnas finales

In [ ]:
data_model_ml.columns

## REGRESION LINEAL MULTIPLE

In [ ]:
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn import datasets
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [ ]:
# defino features y variable de estudio/target
features = ['rooms_new', 'surface_total_in_m2_new',"surface_covered_in_m2_new", 'price_new', 'apartment', 'house', 'store']

X = data_model_ml[features]
y = data_model_ml.price_usd_per_m2_new

In [ ]:
# dividimos en conjuntos de datos para train y test del modelo
x_train, x_test, y_train, y_test = train_test_split(X, y, random_state = 1)
x_train

### Primero se escalan las features y se ajusta el modelo con statsmodels

In [ ]:
# se escalan las features
scaler = MinMaxScaler()
scaler.fit(x_train)

std_numerical_data = scaler.transform(x_train)
x_train_s = pd.DataFrame(std_numerical_data)


In [ ]:
# Restablecer los índices de X e y para asegurar que estén alineados
x_train.reset_index(drop=True, inplace=True)
y_train.reset_index(drop=True, inplace=True)

In [ ]:
# Tenemos que agregar explícitamente a una constante:
x_train_c = sm.add_constant(x_train_s)

# creamos el modelo y lo ajustamos
model = sm.OLS(y_train, x_train_c).fit()

In [ ]:
model.summary()

### TESTEO del modelo

In [ ]:
# Escalar las features de prueba con el mismo scaler utilizado para los datos de entrenamiento
std_numerical_data_test = scaler.transform(x_test)
x_test_s = pd.DataFrame(std_numerical_data_test)

# Agregar explícitamente la constante a los datos de prueba
x_test_c = sm.add_constant(x_test_s)

# Realizar predicciones en el conjunto de prueba
y_pred = model.predict(x_test_c)

# Visualizar las predicciones
print(y_pred)


In [ ]:
print ('R2:', metrics.r2_score(y_test, y_pred))
print ('MAE:', metrics.mean_absolute_error(y_test, y_pred))
print ('MSE:', metrics.mean_squared_error(y_test, y_pred))
print ('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

### SE REALIZA EL MISMO MODULO UTILIZANDO LA LIBRERIA SKLEARN

In [ ]:
# Instanciar el modelo
lm = linear_model.LinearRegression()

In [ ]:
# Vuelvo a separar en TRAIN_TEST porque uso otra libreria.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35)
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model_skl = lm.fit(X_train, y_train)

In [ ]:
# Testeo del modelo
yPred_skl = model_skl.predict(X_test)

In [ ]:
print ('Intercept = ', model_skl.intercept_)
print ('RM = ', model_skl.coef_)

In [ ]:
print ('R2:', metrics.r2_score(y_test, yPred_skl))
print ('MAE:', metrics.mean_absolute_error(y_test, yPred_skl))
print ('MSE:', metrics.mean_squared_error(y_test, yPred_skl))
print ('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, yPred_skl)))

In [ ]:
y_pred_LR = yPred_skl

* Se realiza regularización para mejorar el modelo, avitando así el overfit del mismo

## RIDGE CON CROSS VALIDATION

In [ ]:
# Instanciamos un modelo del tipo Ridge con Cross Validation
rlmcv = linear_model.RidgeCV(alphas=np.linspace(0.1, 100, 100), cv=3, scoring='r2')

In [ ]:
rlmcv.alphas

In [ ]:
rlmcv.fit(X_train, y_train)

In [ ]:
print("El mejor Alpha(lambda) de ajuste:", rlmcv.alpha_)

In [ ]:
print("r^2:", rlmcv.score(X_train, y_train))

In [ ]:
yPred_R = rlmcv.predict(X_test)

In [ ]:
print("r^2 test:", rlmcv.score(X_test, y_test))

In [ ]:
print ('R2:', metrics.r2_score(y_test, yPred_R))
print ('MAE:', metrics.mean_absolute_error(y_test, yPred_R))
print ('MSE:', metrics.mean_squared_error(y_test, yPred_R))
print ('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, yPred_R)))

In [ ]:
y_pred_R = yPred_R

## LASSO CON CROSS VALIDATION

In [ ]:
lassocv = linear_model.LassoCV(alphas=np.linspace(0.01, 100, 1000), cv=3, normalize=False)

In [ ]:
lassocv.fit(X_train, y_train)

In [ ]:
lassocv.coef_ 

### vemos que usando lasso no se elimino ningun coeficiente . . . 

In [ ]:
lassocv.intercept_

In [ ]:
print("r^2:", lassocv.score(X_train, y_train))

In [ ]:
yPred_L = lassocv.predict(X_test)

In [ ]:
print("r^2 test:", lassocv.score(X_test, y_test))

In [ ]:
print ('R2:', metrics.r2_score(y_test, yPred_L))
print ('MAE:', metrics.mean_absolute_error(y_test, yPred_L))
print ('MSE:', metrics.mean_squared_error(y_test, yPred_L))
print ('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, yPred_L)))

In [ ]:
y_pred_L = yPred_L

### Sección gráfica

#### A continuación se puede ver la correlación para las dos variables númericas que utilizaremos para nuestro modelo. A medida que aumenta la sup. total, la sup. cubierta y la cantidad de cuartos, disminuye el precio por m2.

In [ ]:
sns.regplot(data=data_model,x="surface_total_in_m2_new",y="price_usd_per_m2_new",line_kws=dict(color="m"), scatter_kws=dict(color="c"))
plt.xlabel("Superficie total m2")
plt.ylabel("Precio por m2")
plt.show()

In [ ]:
sns.regplot(data=data_model,x="rooms_new",y="price_usd_per_m2_new",line_kws=dict(color="r"), scatter_kws=dict(color="y"))
plt.xlabel("Ambientes")
plt.ylabel("Precio por m2")
plt.show()

In [ ]:
sns.regplot(data=data_model,x="surface_covered_in_m2_new",y="price_usd_per_m2_new",line_kws=dict(color="r"), scatter_kws=dict(color="y"))
plt.xlabel("Superficie cubierta en m2")
plt.ylabel("Precio por m2")
plt.show()

### Análisis de variables categoricas

### Vemos diferencias entre los promedios de precios por tipo de propiedad, lo que indica que existe correlación entre el precio por metro cuadrado y el tipo de propiedad.


In [ ]:
df_group_property = data_model.groupby('property_type_new')
df_resume = df_group_property ['price_usd_per_m2_new'].mean()
colors = sns.color_palette("Set3", len(df_resume))
plt.bar(data_model["property_type_new"].value_counts().index,df_resume, color=colors)
plt.xlabel("Tipo de propiedad")
plt.ylabel("Precio por m2")
plt.show()

In [ ]:
df_group_place_name = data_model.groupby('place_name_new')
df_resume = df_group_place_name ['price_usd_per_m2_new'].mean().sort_values(ascending=False).head(10)
plt.figure(figsize=(22,22))
colors = sns.color_palette("husl", len(df_resume))
plt.bar(df_resume.index,df_resume, color=colors, alpha=0.5, width=0.5)
plt.rcParams["figure.figsize"] = (22,10)
plt.xlabel("Localidad")
plt.ylabel("Precio promedio por m2")
plt.show()

In [ ]:
df_resume = df_group_place_name ['price_usd_per_m2_new'].mean().sort_values(ascending=False).head(10)
df_resume

In [ ]:
fig, ax = plt.subplots()
ax.plot(y_test.values[0:10].astype(int), marker = "o", label = "Datos reales")
ax.plot(y_pred_LR[0:10].astype(int), marker = "o", label = "Modelo de regresión")
ax.plot(y_pred_R[0:10].astype(int), marker = "o", label = "Modelo de Ridge con Cross Validation")
ax.plot(y_pred_L[0:10].astype(int), marker = "o", label = "Modelo de Lazzo con Cross Validation")
ax.legend()
plt.show()

### Por último, entrenamos el modelo agregando variables dummies para cada provincia. Observamos una mejora de dos puntos porcentuales en el accuracy.

In [ ]:
dummies_state_name = pd.get_dummies(data_model_ml.state_name_new, drop_first= True)
data_model_ml = pd.concat([data_model_ml, dummies_state_name], axis=1)

In [ ]:
# defino features y variable de estudio/target
features = ['rooms_new', 'surface_total_in_m2_new',"surface_covered_in_m2_new", 'price_new', 'apartment', 'house', 'store','Bs.As. G.B.A. Zona Oeste', 'Bs.As. G.B.A. Zona Sur',
       'Buenos Aires Costa Atlántica', 'Buenos Aires Interior',
       'Capital Federal', 'Catamarca', 'Chaco', 'Chubut', 'Corrientes',
       'Córdoba', 'Entre Ríos', 'Formosa', 'Jujuy', 'La Pampa', 'La Rioja',
       'Mendoza', 'Misiones', 'Neuquén', 'Río Negro', 'Salta', 'San Juan',
       'San Luis', 'Santa Cruz', 'Santa Fe', 'Santiago Del Estero',
       'Tierra Del Fuego', 'Tucumán']

X = data_2[features]
y = data_2.price_usd_per_m2_new

In [ ]:
# Instanciar el modelo
lm = linear_model.LinearRegression()

In [ ]:
# Vuelvo a separar en TRAIN_TEST porque uso otra libreria.
semilla = 42
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, , random_state = semilla)
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model_skl = lm.fit(X_train, y_train)

In [ ]:
# Testeo del modelo
yPred_skl = model_skl.predict(X_test)

In [ ]:
print ('Intercept = ', model_skl.intercept_)
print ('RM = ', model_skl.coef_)

In [ ]:
print ('R2:', metrics.r2_score(y_test, yPred_skl))
print ('MAE:', metrics.mean_absolute_error(y_test, yPred_skl))
print ('MSE:', metrics.mean_squared_error(y_test, yPred_skl))
print ('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, yPred_skl)))

In [ ]:
y_pred_LR = yPred_skl

### Volvemos a probar con Lasso

In [ ]:
lassocv = linear_model.LassoCV(alphas=np.linspace(0.01, 100, 1000), cv=3, normalize=False)

In [ ]:
lassocv.fit(X_train, y_train)

In [ ]:
lassocv.coef_ 

### vemos que usando lasso no se elimino ningun coeficiente . . . 

In [ ]:
lassocv.intercept_

In [ ]:
print("r^2:", lassocv.score(X_train, y_train))

In [ ]:
yPred_L = lassocv.predict(X_test)

In [ ]:
print("r^2 test:", lassocv.score(X_test, y_test))

In [ ]:
print ('R2:', metrics.r2_score(y_test, yPred_L))
print ('MAE:', metrics.mean_absolute_error(y_test, yPred_L))
print ('MSE:', metrics.mean_squared_error(y_test, yPred_L))
print ('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, yPred_L)))

In [ ]:
print ("y_test sample: ",y_test.values[0:10].astype(int))
print ("y_pred sample: ",yPred_L[0:10].astype(int))

### Vemos las predicciones versus los testeos.

In [ ]:
fig, ax = plt.subplots()
ax.plot(y_test.values[0:10].astype(int), marker = "o", label = "Y_test_sample")
ax.plot(yPred_L[0:10].astype(int), marker = "o", label = "y_pred_sample")
ax.legend()
plt.show()